# Retter med kylling

## Hverdagskylling med kremede svampe

Fra food52

* ½ kg svampe
* 4 spsk smør
* ½ kg kyllingebryster - Oprindeligt var det 1 kg
* 2½ dl piskefløde (eller madlavningsfløde)
* 2 spsk dijon sennep
* finthakket purløg

Rens svampene, skær halvdelen i skiver, og resten i kvarter.

* Smelt 2 spsk smør, 
* tilføj svampene, steg dem 10-15 minutter, til
de begynder at karamelisere. 
* Halver kyllingebrysterne på langs,
og bank dem med kødhammeren, ca 1/4 tomme så - 40 millimeter?
* dub dem af, og krydr med salt og peber.
* Giv svampene lidt salt og peber, deglacer med 1/3 cup vand.
* Smelt resten af smørret, steg kyllingerne. Smid gerne en 
bøfpresse ovenpå dem.
* Bland fløde og sennep. Rør dem i svampene, og kog under omrøring
til den tykner. Smag til med salt, peber og sennep.
* Saml - kylling overhældes med svamep. Vi serverer med ris.

# onepot chicken & rice
Fra noma

* 60 g olie
* 4 kyllige lår uden ben, med skin
salt
140 gram løg finthakket
3 fed hvidløg smadret
15 g tomatpasta
60 g hvid miso
15 g røget paprika

80 g røget svampe garum
600 g grøntsagsbouillon

10 g salt
200 g ris
10 g persille
200 g mayonaise
1 fed hvidløg - revet.

sautepande - olie varmes op unmder middel varme. krydr kyllingerne med generøse mængder 
salt. Når olien simrer, brunes kyllingen. til den er mørkebrun og sprød. ca. 4 minutter.
fjern kyllingerne fra panden. Skru ned til lav varme.
tilsæt løg og hvidløg. Steg til løgene er klare.
rør tomatpastaen i og steg ca. 5 minutter til tingene er rustent brune.
Tlilsæt bouillon, stalt, røget svampe garum, parpirka og miso. Øg temperatren til høj. Rør for at 
blande.

Når væsken koger, tilsæt risene og rør så de er jævnt fordelt. Her fra skal risene ikke røres!

Skru ned for varmen, og lad den simre. tilføj kyllingerne til gryden, med den rå side ned. (så ved stegningen
er det kun på skindsiden at den skal steges!) Når duften af brændte ris kan mærkes - efter ca. 20-25 minutter
er vi ca. færdige. tag af varmen, og lad hivle i 5 minutter. pynt med hakket persille.

Bland mayo med hvidløg og bland godt. 

Server portioner af ris på tallerken - husk at få det sprøde let brændte lag med. Kylling på toppen.
Top yderligere med hvidløgsmayo.




## pollo orzo
One pot. Og relativt hurtig.

Orzo er de der små rislignende pastating. 

* Kyllingestykker. Helst med ben. En samling lår er fint.
* 3 fed hvidløg
* 2 tsk salt
* peber
* 1½ liter vand
* ~½ liter kyllingefond.
* En dåse hakkede tomater
* 1 løg eller to hvis det er et lille løg
* 340 gram orzo pasta
* persille

Brun killingerne i olie/smør/andefedt/margarine
ca. 5 minutter på hver side.

Tag killingerne op, og brun pastaen let i fedtstoffet.

Tilsæt finthakket løg og klar løgene. Smid finthakket hvidløg i til sidst.

Læg killingerne tilbage i panden.

Hæld fond og tomater over.

Låg på, og lad simre 10-15 minutter, afhængig af orzo type og killing.
Pastaen skal være al dente, killingen skal være gennemstegt/kogt.

Tag gryden af varmen, og lad den hvile i 5 minutter. Orzoen skal gerne absorbere
stort set al væden. Hvis det skal være ekstra festligt, så hæld persille over.