# Desserterne

## Pistacie is

* 5 dl fløde
* 2 dl sødmælk
* 100 g + 2 spsk sukker
* 153 g æggeblommer (ca 8 stk)
* 136 g pistacienødder
* 0.2 g carragenan

Nødderne hakkes fint på maskine. Fløde,
mæld og hakkede nødder bringes op til ca.
75 grader c - og trækker i ca 1 time.
Derefter stavblendes blandingen, og 
bringes op til 85 grader C.

Imens piskes æg og sukker til det er hvidt
og skummende. Æggesnapsen tempereres med
mælken og bringes tilbage til gryden.
carragenan tilsættes, og det hele varmes op
til 80 grader. 
Køler af og køres på ismaskinen.

## Salt og peber is

* 454 gram piskefløde
* 1 spsk sorte peberkorn
* ½ tsk sorte peberkorn
* 150 gram sukker
* 1 spsk vodka
* ½ tsk salt
* flage salt

knus 1 spsk peberkorn groft i en morter. 
varm fløden op til den damper. tag af varmen, og rør de 
knuste peberkorn i. Lad det trække en time - rør regelmæsigt.
Knus ½ tsk peber fint.


Sig fløden og smid peberkornene ud. Tilføj sukker,
vodka og salt, og rør indtil sukkeret er opløst.
Rør det fintmalede peber i. Dæk og køl til meget 
koldt, mindst et par timer, op til en dag.

Pisk flødeskummen til meget bløde toppe.

Frys 8 - 12 timer. 

Smid lidt flagesalt på toppen.



Hertil kan serveres en salt og peber brittle.

* 1 tsk sorte peberkorn
* ½ kop (99 gram) sukker
* flagesalt.

Mal peberen - vi skal have et mix af groft og fint.
Dæk bageplade med bagepapir.
Smid sukkeret i en lille kaserolle, og giv den 3
spsk vand. Bring i kog over middel varme,
og kog til det har samme farve som mørk ahornsirup.
Undgå at røre, swirl kaserollen i stedet. 
Så snart karameliseringen er sket - tages den af varmen, og der røres (silikoneredskaber er din ven her) stødt peber . Over på bagepapiret - spred ud så tyndt som muligt, så hurtigt som jmuligt. Og spred
flagesalt over med det samme!

Lad det køle helt ned - mindst 15 minutter, knus til mindre stykker - og opbevar i luftæt beholder.

## Kæmpe E-ords isdessert

Solbærting
* 400 g solbær
* 200 g sukker
* 2 spsk. citronsaft
* 2 spsk. vand

isen
* 5 dl piskefløde
* 5 æggeblommer
* 100 g rørsukker

Sjokoladesovsen
* 50 g god mørk chokolade (ca. 70% kakao)
* 1/2 dl fløde

Solbærtingen:
Kom alt i en gryde, kog ca. 10 minutter. Lad det køle af.

Flødeisen:
Kom alt i en skål, og pisk til en let skum.

Samling
Kom solbærtingen i en skål (eller springform eller isform eller noget), der kan rumme
mindst 1½ liter. Hæld ismassen over. Rør forsigtigt rundt. Det skal ikke være 
homogent, men der skal være striber af solbær i isen. Og de fleste af bærrene
skal blive i bunden. Den bliver nemlig toppen når du vender isen ud.
Frys isen i mindst 4 timer. Rør i den 2-3 gange de første par timer
hvis du vil mindske risikoen for krystaller.

Sjokoladesaucen
Kan chokoladen mellemfint. Bring fløde i kog, tag den af varmen, og rør
chokoladen i til sovsen er glat.

Vend isen ud på et tallerken eller fad. Hæld chokoladesovsen over toppen af 
islagkagen ved servering. Pynt evt med solbær og/eller solbærblade.


## Fransk nougat
Det er ikke sundt... Men det smager godt.

200 gram mandler
75 gram usaltede pistacenødder
75 gram æggehvider
125 ml vand
250 gram melis
100 gram glukosesirup
150 gram honning
Flormelis.

For en firkantet beholder på ca. 15x15 cm med bagepapir og et solidt drys flormelis.

Smut mandlerne, og rist dem ved 180 grader i et kvarter (i ovnen)

Rist dernæst pistacienødderne i 7 minutter ved samme temperatur

Hæld vand, sukker og sirup i en tykbundet gryde, og bring det i kog. Massen smeltes sammen, og varmes op til 140 grader. Så du skal have et sukkertermometer (eller andet der kan klare den slags temperaturer).

Et tip er at lægge låg på et par gange undervejs. Kondensvand under låget vil løbe ned langs grydens kanter, og bringe sukkerkrystaller ned i blandingen.

Når sukkerblandingen har nået 140 grader, tilsættes honningen, og du koger videre til temperaturen når 150 grader, og gryden tages straks af.

Pisk æggehviderne luftige (gør det mens du venter på at temperaturen stiger), og hæld sukkermassen i i en tynd stråle mens der piskes (ved lav hastighed). Så pisker du ved medium hastighed indtil massen er lun. Det tager ca. et kvarter.

Når den har fået konsistens som en meget sej marengs, æltes de ristede nødder i.

Så hældes hele massen i beholderen. Giv den et solidt drys flormelis ovenpå, og tryk massen jævn. Lad den hvile til dagen efter, og skær den ud i passende stykker med en brødkniv.


## Spinatis

Vist oprindeligt fra Irma.

* 60 gram rå cashewnødder
* 1 dåse kokosmælk. Ikke light!
* 2 modne avokadoer
* 1 moden banan
* 2 store håndfulde spinat
* 4 spsk sirup (agave. Ahorn hvis det er hvad jeg har)
* 2 tsk vanillepulver

Nødderne udblødes i 12 timer. Det faste fedt fra kokosmælken (så ikke den flydende fraktion af dåsen) samt alle andre ingredienser (også nødderne) kommes i blenderen, og blendes til blandingen er jævn og kremet.

Blandingen sættes i fryseren 5-6 timer. Eller natten over. Står den hele natten er den vanskelig at arbejde med.


## Rødvins is!

Stærkt inspireret af denne: https://www.bhg.com/recipe/red-wine-ice-cream/

Den opskrift forudsætter at man har en rest rødvin til overs. Det sker ikke så ofte, og når det gør, bliver den hældt i eddikekrukken. Men så kan man jo twiste opskriften lidt. Det er den under alle omstændigheder.

Ingredienser:

* 400 gram frosne jordbær
* 500 gram frosne blåbær (eller hvad det nu er - det rant gemmer vi til senere)
* 450 gram sukker
* 3 dl rødvin (gerne tør)
* 2 spsk balsamico eddike
* 2½ cm frisk ingefær i skiver
* 1 tsk vanille ekstrakt
* ½ tsk salt

Procedure:

Alt hældes i en gryde, og der varmes op under middel varme, indtil al sukker er gået i opløsning, og bærrene er helt bløde.
Blandingen tages af blusset, og får lov at køle af. Ingefæren fiskes op. Det er en god ide at have styr på ca. hvor mange skiver der er kommet i, så man er sikker på at man har fået fisket dem alle op.
Blandingen hældes enten på blender, eller får med stavblenderen til alt er homogent. Kør gerne massen gennem en sigte - jeg gider ikke alle jordbærkernerne.
Kør massen på ismaskine, eller smid den i fryseren. Har du ikke en ismaskine, rører du regelmæssigt rundt i ismassen mens den fryser ind. Har du mulighed for at hælde den i en bradepande er det helt perfekt. Ismassen har ikke været varmere end at der stadig er alkohol tilbage, så det tager noget længere end ellers at få den frosset.

Server med flødeskum, og evt. sort peber eller kanel. Ja, det fungerer faktisk godt med peber - men brug en kværn der kværner peberen fint, i stedet for groft.

Næste gang prøver jeg at hælde mere rødvin i. Vinen fylder ikke meget i smagsbilledet.



## Rabarber-jordbær trifli med ginflødeskum

Trifli til 4 personer

Kompot:
* 250 g rabarberstænger
* 250 g jordbær
* 1 stang vanilje
* 1/2 dl vand
* 2 spsk. appelsin- eller citronsaft
* 150 g sukker

Desuden:
* 12 makroner
* 4 spsk. gin

Ginflødeskum:
* 3 dl piskefløde
* 50 g sukker
* 1/2 dl gin
* korn af den flækkede vaniljestang

Pynt:
lidt knuste makroner og rød skovsyre

Rens og skær rabarberstængerne i 1 cm skiver. Rens og skyl jordbærrene, og skær 
dem i kvarte. Skrab kornene ud af vaniljestangen. 
Kog frugten op i en gryde med vand, appelsinsaften og den tømte vanilliestang
i ca. 5 minutter.
Tilsæt sukker og kog videre til det er opløst. Afkøl. Fjern vanillien.

Lav isbad med 3-4 dl isterninger og koldt vand. Sæt en skål med fløde,
gin og 50 gram sukker i. Pisk sammen til bløde toppe.

Knus makroner og læg i glas. Dryp med goin. Kom kompot i. Kom ginflødeskum i.
pynt med knuste makroner. evt også et blad mynte eller lignenden.

## chokolademus
250 g økologisk bæredygtig kogechokolade, 70 eller 80 pct.
50 g sukker 6 økologiske æg, eventuelt pasteuriserede Et sprøjt citron En knivspids salt
Eventuelt 50 g smør Eventuelt 1-2 teskefulde espresso Eventuelt revet appelsinskal Bræk
chokoladen i stykker, og smelt den på lavt blus i et vandbad.
Det er her, at smørret kan tilføjes. Smelter du smør med chokoladen, vil den blive lettere
at blande sammen med både blommerne og senere æggehviderne.

Slå æggene ud, og skil blommerne fra hviderne.
Læg fire æggeblommer til side.
Pisk æggehviderne med en knivspids salt og et lille sprøjt citronsa

. Tilføj sukker til sidst

for at få de piskede hvide til at stivne yderligere.
Bland æggeblommerne med den smeltede chokolade. Den smeltede chokolade må ikke
være så varm, at blommerne koagulerer, men varm nok til, at den forbliver flydende og
kan blandes sammen med resten af ingredienserne.

Du kan komme en eller to teskefulde espresso i chokoladen, som forstærker
chokoladesmagen og gør den en snært mere flydende.
Riv eventuelt en smule økologisk appelsinskal i den smeltede chokolade, men vær
forsigtig, da den nemt kan overdøve smagen.
Lø
chokoladefadet ud af sit vandbad, og lad den køle en smule af. Den må ikke være
brændende varm, men skal stadig være lun og flydende.
Hæld først lidt af den smeltede chokolade op i æggeblommerne, bland det forsigtigt, og
kom here

er gradvis æggeblommerne i den smeltede chokolade, som skal bevare sin

glatte flydende tekstur.
Hæld lidt af den piskede æggehvidemasse op i chokoladeblandingen, så den bliver
lettere.
Bland det blødt sammen. Hæld gradvis chokoladen i æggehvideblandingen. Fortsæt
med at vende det rundt med smidige bevægelser, et godt tempo og en sikker hånd, til
blandingen får en jævn farve, uden at æggehviddernes stivelse falder. Det er
blandingerne, der kræver opmærksomhed, men det er ikke så omstændeligt, som det
kan lyde.

Din mousse er nu klar til at blive hældt op i små portionsskåle, i glas eller i en stor skål.
Lad den hvile tildækket i køleskabet i minimum 4 timer. Og så har du en evigt god
klassisk dessert, som for en sikkerheds skyld helst skal spises inden for 24 timer, da
æggene er rå.


## Sifon opskrift – Bacardi krem

Krem som i kagekrem.

1 æg (pasteuriseret)
125 ml piskefløde
1-2 spsk bacardi rom – jeg ville gå efter en mørk udgave, men det er en smagssag
1 spsk flormelis

Rør det hele samme, sørg for at sukkeret er helt opløst, og hæld det på sifon. Giv den 1 skud lattergas, og ryst grundigt.

## Vanilleis

Oprindeligt publiceret 27. august 2015.

Kæresten er til kor. Jeg har alfabetiseret krydderierne (stærkt inspireret af denne side – eller strengt taget af denne bog, som jeg fik til min fødselsdag) og jeg har kogt den hjemmelavede rødvinseddike.

Det startede som en overspringshandling, fordi jeg ikke kunne tage mig sammen til at læse erhvervsøkonomi. Som jeg startede med at tage mig sammen til at gøre noget ved, i stedet for at pille mere ved den hjemmeside som kæresten har lovet at lave for en forening der står os begge nær (Copenhagen Pride). Opvasken trængte til at blive taget. Men det er jo ikke sjovt, så hellere kreere et eller andet i køkkenet. Lad mig se, det er vist en tredobbelt overspringshandling. Anyways. Næste projekt, for at undgå at gøre hvad jeg burde gøre, er vanilleisen. 

Jeg bruger denne opskrift, som jeg har tyvstjålet fra Kvalimad-bloggen (den holder hvad navnet lover!), men som jeg ikke har dårlig samvittighed over at kopiere her, fordi jeg har modificeret den let.




5 dl piskefløde
2 dl mælk
3 hele æg, eller 8 blommer.
150 gram sukker (Du kan nøjes med 100 gram hvis du syntes den er for sød.)
1 stangfuld vanillekorn
1 spsk vanilleessens

Det hele hældes i gryden, varmes op til 85 grader, og smides på ismaskinen. Og derefter kommer det i fryseren og er forhåbentlig klar til kæresten arriverer kl. 23. 

Tilføjelsen er vanilleessensen. Den er hjemmelavet, og står og hygger sig i en flaske i et af skabene. Den er rekursiv. Vanillestangen der leverede kornene, bidrager nemlig til næste portion essens.

Det går i al sin enkelthed ud på, at man går i barskabet og finder en flaske vodka. Den hælder man på en passende flaske, i hvilken man har placeret en brugt vanillestang. Efterhånden som man bruger af den, fylder man ekstra brugte stænger og vodka på. Helt simpelt.

Jeg kickstartede processen ved at smide et par stænger i sifonen sammen med 2½ dl vodka, sætte den under tryk med lattergas, og så hurtigt udløse trykket efter et par minutter. Jeg må hellere vende tilbage til teknikken i det på et senere tidspunkt, men det accellererer ekstraktionen af smagsstoffer.

## Sifon vanille is

Pisk 25 g sukker med 2 pasteuriserede æggeblommer og kornene af ½ vanillestang, til en luftig æggesnaps.

Hæld 111 ml fløde og 2 pasteuriserede æggehvider (tag bare to bægre æggehvide – det går nok at det er lidt mere end 2 hvider).

Hæld blandingen på sifonflasken, tilsæt to patroner lattergas, og ryst et par gange. Pas på at du ikke ryster for meget, så bliver fløden for stiv.

Skyd ismassen i en beholder på ca. en liters penge, og stil det hele i fryseren et par timer.

Man kan evt. stille beholderen i fryseren på forhånd. Men det giver mest mening hvis det er en metalbeholder man bruger. Laver du din is i en plastbeholder, har den så lidt termisk masse, at det ikke gør nogen forskel.

## appelsinsorbet

Selvkomponeret. Men stærkt inspireret, ja nærmest kopieret, fra et tidligere eksperiment:

½ l appelsinjuice
160 g sukker
1½ æggehvide

Juice og 125 g sukker koges sammen og afkøles. 

Æggehvide og resten af sukkeret røres til marengs

Sukkerlagen hældes på ismaskinen og hygger sig en halv times tid. Herefter tilsættes marengsen, og sorbeten fryser færdig.

I modsætning til æblesorbeten, som fik klager over hvor sød den var, passede det meget bedre her. Det gør sikkert en forskel om det er "16 søde appelsiner", eller den billigste, sureste juice (det var den billigste fra Føtex). Men resultat var fremragende.


## Jordbæropskrift fra Falsled Kro

Planket direkte fra en opskrift i et turistmagasin for Fyn 2020. Det er køkkenchef Kasper Tind Hasse fra Falsled Kro (og så bliver det ikke meget finere på den side af Storebælt) der har kreeret.

Brændte jordbær med inspiration fra haven

Den består af flere elementer:

Citronconfit

2 øko-citroner

200 g sukker

½ liter vand

Skræl, kun det gule!, citronerne og gem skrællen. Fjern den hvide hinde, og kernerne fra frugtkødet. Skrællen og frugtkødet koges med vand og sukker til det tykner og begynder at karamellisere. Det skal blive mørkegult. Blend og sigt massen.

Citronsorbet

1 dl citronsaft

4 dl vand

100 g sukker

2 blade husblas

100 g citronkonfit

Læg husblas i blød i koldt vand. Giv resten af ingredienserne et kort opkog. Tag blandingen af blusset, vrid husblassen, og rør den i den varme blanding til den er helt opløst. Stil den på køl til den skal på ismaskinen.

Jordbær

Friske jordbær

God, grøn olivenolie

Birkesirup (eller let fortyndet blomsterhonning)

Sort og rosa peber

Søde og aromatiske krydderurter. Hvad man nu har adgang til. Timianblomster, solbær, jernurt, den slags. Men frisk, ikke tørret.

Jordbærrene renses og skæres i halve. Halvdelen karamelliseres på en meget varm pande på skærefladen - 1-2 minutter. Alle bærene marineres i olivenolie og birkesirup i forholdet 1:1, med et kværn sort peber og 10 knuste rosapeberkorn.

Anretning:

Jordbær og urter vendes sammen, citronsorbeten (husk at give den en tur på ismaskinen!) kommes på toppen, og anretningen overhældes med en sjat af marinaden fra jordbærrene.

## Æblesorbet

En opskrift fra ismaskinen.dk.

½ l æblejuice
160 g sukker
1½ æggehvide

Juice og 125 g sukker koges sammen og afkøles. 

Æggehvide og resten af sukkeret røres til marengs

Sukkerlagen hældes på ismaskinen og hygger sig en halv times tid. Herefter tilsættes marengsen, og sorbeten fryser færdig.


## Lys, eller hvid, chokolade creme på sifon

En, relativt hurtig, opskrift på lys chokoladesovs, eller creme om du vil, fremstillet på sifon. Antallet af ingredienser er så lavt at det næsten kvalificerer til kategorien "simpel mad", men anvendelsen af sifon og lattergas bringer os klart over i det mere avancerede køkken.

1 1/8 dl fløde
187 g hvid (eller lys) chokolade
3 æggehvider

Hviderne skal helst være pasteuriserede. Opskriften passer med to bægre æggehvider. Og 112,5 ml fløde er intet problem i et køkken der bruger måleglas og laboratorievægte… Med to æggehvider lander vi på 3/4 dl fløde, og 125 g chokolade.

Chokoladen smeltes, rutinerede kokke gør det direkte på blusset, mere forsigtige typer på vandbad. Det går under alle omstændigheder hurtigst hvis den først har fået lidt tæsk med kagerullen, så den er i små stykker. Fløden varmes – uden at koge, så kommer det til at smage af risengrød – og hældes på chokoladen. Rør til blandingen er pænt glat og ensartet. Rør herefter hviderne i.

Hæld blandingen på sifonflasken, og giv den to skud lattergas. Stil den i varmt vand – ca. 60 grader – en times tid. Og så er den klar til servering.

## chokolade sifon kage

Det lykkedes ikke at finde majsjuice. Thaiforretningerne nede ved Istedgade har mange andre interessante produkter, men ikke majsjuice.

Så i stedet lavede jeg denne:

110 g mørk chokolade
5 mindre æg
3 spsk mel
6 spsk sukker

Chokoladen smeltes, og resten røres i. Det hele filtreres og hældes på sifonen. To kapsler lattergas tilsættes. Den anden blev ikke tømt helt i sifonen.

Der omrystes, og sprøjtes i ramekinerne (teflonbelagte), og en ramekin af gangen gives 30-45 sekunder i mikroovnen ved 900 W. Bemærk at ramekinen ikke er specielt varm efter første omgang. Men efter anden er den varmet op, tredie gang den har været i ovnen er den varm, selv for en kemiker. Hold godt øje med kagen i ovnen. Den får hurtigt for meget.

Det er ikke sundt, men det smager godt, og så her det stor nørdværdi. Opskriften er tyvstjålet fra: http://projects.washingtonpost.com/recipes/2010/12/01/30-second-chocolate-cake/ med lette modificeringer.

http://projects.washingtonpost.com/recipes/2010/12/01/30-second-chocolate-cake/


## Sellerisorbet

Kæresten kan ikke lide selleri. Virkelig ikke!

Så en af de kommende torsdage (oprindeligt skrevet 27. august 2015, der skulle laves regnskab i Copenhagen Pride), når jeg er korenkemand, er bogholderen inviteret forbi, og når vi har kigget lidt på bilagene, skal der spises ting med selleri. Det bliver nok relativt enkelt, med en høne i noget asparges og sådan. Med en kartoffelmos med tilsat knoldselleri. Og så lidt ekstra. Det ekstra bliver sellerisorbet.

Man tager:

177 ml vand
118 ml sukker
1 l groft hakket selleri
1 spsk limesaft
1 tsk lime skal

Opløs sukkeret i vand, gerne over varme, og lad køle helt af.

Hæld sukkeropløsningen over sellerien, limesaften og limeskallen, og blend. Ja, faktisk skal der pureres. Smid pureen på køl natten over. Si blandingen, og lad den gerne stå i køleskabet henover dagen, så al væden drypper fra. Hæld væden i ismaskinen, og lad den fryse.

Server direkte fra ismaskinen, eller lad den stå i fryseren i op til et par dage (så bliver den fuldstændig hård, og er nok snarere en granité end en sorbet)

Smager det godt? Ikke rigtigt. Det skal bruges sammen noget andet.

