# Desserterne


## Salt og peber is

454 gram piskefløde
1 spsk sorte peberkorn
½ tsk sorte peberkorn
150 gram sukker
1 spsk vodka
½ tsk salt
flage salt

knus 1 spsk peberkorn groft i en morter. 
varm fløden op til den damper. tag af varmen, og rør de 
knuste peberkorn i. Lad det trække en time - rør regelmæsigt.
Knus ½ tsk peber fint.


Sig fløden og smid peberkornene ud. Tilføj sukker,
vodka og salt, og rør indtil sukkeret er opløst.
Rør det fintmalede peber i. Dæk og køl til meget 
koldt, mindst et par timer, op til en dag.

Pisk flødeskummen til meget bløde toppe.

Frys 8 - 12 timer. 

Smid lidt flagesalt på toppen.



Hertil kan serveres en salt og peber brittle.

1 tsk sorte peberkorn
½ kop (99 gram) sukker
flagesalt.

Mal peberen - vi skal have et mix af groft og fint.
Dæk bageplade med bagepapir.
Smid sukkeret i en lille kaserolle, og giv den 3
spsk vand. Bring i kog over middel varme,
og kog til det har samme farve som mørk ahornsirup.
Undgå at røre, swirl kaserollen i stedet. 
Så snart karameliseringen er sket - tages den af varmen, og der røres (silikoneredskaber er din ven her) stødt peber . Over på bagepapiret - spred ud så tyndt som muligt, så hurtigt som jmuligt. Og spred
flagesalt over med det samme!

Lad det køle helt ned - mindst 15 minutter, knus til mindre stykker - og opbevar i luftæt beholder.

## Kæmpe E-ords isdessert

Solbærting
400 g solbær
200 g sukker
2 spsk. citronsaft
2 spsk. vand

isen
5 dl piskefløde
5 æggeblommer
100 g rørsukker

Sjokoladesovsen
50 g god mørk chokolade (ca. 70% kakao)
1/2 dl fløde

Solbærtingen:
Kom alt i en gryde, kog ca. 10 minutter. Lad det køle af.

Flødeisen:
Kom alt i en skål, og pisk til en let skum.

Samling
Kom solbærtingen i en skål (eller springform eller isform eller noget), der kan rumme
mindst 1½ liter. Hæld ismassen over. Rør forsigtigt rundt. Det skal ikke være 
homogent, men der skal være striber af solbær i isen. Og de fleste af bærrene
skal blive i bunden. Den bliver nemlig toppen når du vender isen ud.
Frys isen i mindst 4 timer. Rør i den 2-3 gange de første par timer
hvis du vil mindske risikoen for krystaller.

Sjokoladesaucen
Kan chokoladen mellemfint. Bring fløde i kog, tag den af varmen, og rør
chokoladen i til sovsen er glat.

Vend isen ud på et tallerken eller fad. Hæld chokoladesovsen over toppen af 
islagkagen ved servering. Pynt evt med solbær og/eller solbærblade.


## Fransk nougat
Det er ikke sundt... Men det smager godt.

200 gram mandler
75 gram usaltede pistacenødder
75 gram æggehvider
125 ml vand
250 gram melis
100 gram glukosesirup
150 gram honning
Flormelis.

For en firkantet beholder på ca. 15x15 cm med bagepapir og et solidt drys flormelis.

Smut mandlerne, og rist dem ved 180 grader i et kvarter (i ovnen)

Rist dernæst pistacienødderne i 7 minutter ved samme temperatur

Hæld vand, sukker og sirup i en tykbundet gryde, og bring det i kog. Massen smeltes sammen, og varmes op til 140 grader. Så du skal have et sukkertermometer (eller andet der kan klare den slags temperaturer).

Et tip er at lægge låg på et par gange undervejs. Kondensvand under låget vil løbe ned langs grydens kanter, og bringe sukkerkrystaller ned i blandingen.

Når sukkerblandingen har nået 140 grader, tilsættes honningen, og du koger videre til temperaturen når 150 grader, og gryden tages straks af.

Pisk æggehviderne luftige (gør det mens du venter på at temperaturen stiger), og hæld sukkermassen i i en tynd stråle mens der piskes (ved lav hastighed). Så pisker du ved medium hastighed indtil massen er lun. Det tager ca. et kvarter.

Når den har fået konsistens som en meget sej marengs, æltes de ristede nødder i.

Så hældes hele massen i beholderen. Giv den et solidt drys flormelis ovenpå, og tryk massen jævn. Lad den hvile til dagen efter, og skær den ud i passende stykker med en brødkniv.


