# Diverse og usorteret

## Hvor meget mel skal der i sovsen?
Ja, det er jo en smagssag.

Men i en opbagt sovs:

3 spsk hvedemel til ½ liter væske.

## den faste madplansrotation


## kartoffelfrikadeller

500 gram kartoffelmos
1 revet løg
1 æg
3-4 spsk hvedemel
4-5 spsk rasp
salt og peber

Rør alt sammen, steg dem 2-3 minutter i olie/smør

Nappet fra Maden i mit liv siden. 


https://gastrofun.dk/opskrift/koral-tuille/


Bechamel - Mælk + roux
bliver til
Cream (cream + lemon)
Cheddar (chees, worchestershire sovs, mustard


## Svampe omelet

Også fra Noma

* 20 gram røget svampe garum
* 100 g assorterede svampe - tyndt skåret
* olie
* 30 gram smør
* 1 fed hvidløg - smadret
* 5 gram purløg - hakket
* 2 store æg
* salt og peber

brun svampene i olien i en sauterpande.

tilsæt halvdelen af smøret, og de knuste hvidløg
toss svampene, så de dækkes af hvidløgssmør.
Lad dem stege videre et par minutter, hæld svampe garum over. Steg videre til væsken er reduceret lidt.

Tilføj purløg, og bland. Overfør til skål.

Pisk æggene. 

Hold hånden over en pande 3 cm. i to sekunder. Hvis det er for varmt, skru ned, hvis ikke, skru op.
hæld den anden halvdel af smørreet påå panden og fordel. 
Hæld æg på panden. de skal boble roligt. fordel over hele panden. agiter æggene med en paletkniv.
Toppen skal være løs og creamy. Salt æggene.

fjern panden fra varmen, o hæld svampene ud på midten af omeletten.
Fold omeletten over sig selv, så svampene dækkes. Vi går efter en halvmåne form.

Løft omeletten, og snig en smule smør ind under den. Giv den varme i ca. 30 sekunder. Server.



## bagselv leverpostej i airfryer
Det forlyder - men er ej testet, at den bages direkte fra
frost ved 170 grader i 40 minutter.
Det tester vi så!


## Mississippi Mud Potatoes

Den ondeste comfort food
1½ kg kartofler - skrællet og skåret i mundrette tern (måske lidt større. De svinder)
2½ dl revet cheddar
3/4 kop majonæse
3 smadrede hvidløg
500 g bacon i tern - stegt
½ cup hakket løg

Forvarm ovnen til 170 grader. Sådan ca. Varmluft.
Fedt en bradepande
Smid alt i bradepanden - bland godt så alt er dækket.
Bag hele svineriet i 1½ time - eller til kartoflerne er møre.
Rør gerne undervejs.
Vupti. Overvej hvilken cheddar du bruger. Den billige fra 365 skiller 
fuldstændigt og der er intet gooey eller stretchy over det.

## Curly fries

Du kender dem godt. De der snoede fries du får på fastfood restauranten.

De laves selvfølgelig ikke ved at skære kartoflerne ud på den måde.

I stedet laves de af kartoffelmos.

500 gram kartoffelmos (evt rest)
1 æg
50 gram majsstivelse (også kendt som maizena)
30 gram revet parmasan (fintrevet)
Salt og peber
Neutral olie til stegning

Bland alle ingredienser (bortset fra olien) sammen, og hældt på sprøjtepose. Klip hul i bunden.

Varm olien op til ca. 170 grader (eller der hvor det syder om en tændstik), og sprøjt blandingen ud i olien. Der kan laves spiraler eller andre sjove former.

Friter dem til de er gyldne (og vend dem!). Drypper af på fedtsugende papir.

## Dagens køkkeneksperiment – Quindim
Efter ønske fra svogeren, eller hvad kærestens bror nu skal kaldes når der ikke er papir på familieforholdet, er der blevet eksperimenteret med en brasiliansk kokoskage. Det var ikke nogen stor succes i første omgang. Det kan være vi prøver igen i morgen. Anyway. Quindim kaldes den. Opskriften var som følger:

75 g kokosmel
225 g sukker
1 spsk smør
6 æggeblommer
1½ æggehvide

Kokosmel, sukker og smør blev rørt sammen, blommerne pisket i en af gangen, og den stivpiskede hvide rørt i til sidst. Bagt i en 24 cm springform i vandbad i ovnen ved 180 grader i 30 minutter. Den så godt nok færdig ud efter 20, men det var den ikke. Prik i den med en stegenål.

Tre problemer. Lige nu, men den er ikke helt afkølet, er den ret blød. Den er nærmest sådan lidt buddingblævrende. Det kan rette sig, og så er der den detalje, at den hist og her på nettet kaldes en kokosbudding. Så måske bør den faktisk være lidt blævrende. Andet problem – springforme er ikke vandtætte. Hvor stort et problem det har været venter jeg med at afgøre til den er afkølet – jeg tror det gik. Tredie problem – den er ca. 1 cm høj. Det ligner overhovedet ikke det man finder af billeder på nettet…

Til gengæld er den supernem at gå til, så der er plads til et par eksperimenter til.

# der skal nok være en separat til fisk

## Lax på grønt

Det meste madlavning derhjemme er improviseret, og uden opskrift. Som regel går det godt. Undertiden går det så godt, at jeg bliver opfordret til at gentage successen. Og det er jo et problem - for jeg har sjældent noteret hvad det var jeg gjorde.

Forleden fik jeg lyst til fisk. Der var laks i Fakta. Og her efter jul og nytår ville vi nok ikke tage skade af noget mere grønt, og knap så fedt. Så:

Ingredienser:

3 peberfrugter
2 bundter forårsløg
1 bakke champignon
1 bakke cherrytomater
3 fed hvidløg
1 courgette
4 skiver laks
3 dl hvidvin
1 sjat Pernod
Olivenolie
Salt og peber

Fremgangsmåde:

Tomaterne skylles, og skæres i skiver. De lægges i bunden af et ildfast fad.
Svampene renses og skæres i skiver, og steges (ret hårdt) i olie. Der krydres med salt og peber.
Svampene fordeles over tomaterne.
Courgetterne skrælles let, skæres i ca ½ cm tykke skiver, og steges i olie. Der krydres med salt og peber, og de fordeles i fadet over svampene.
Forårsløg renses og snittes.
Hvidløg pilles og hakkes fint.
Begge løg kommer på panden og steges. De fordeles i fadet over courgetterne.
Peberfrugterne renses, skæres i strimler, der halveres. De steges let på panden med salt og peber. Og fordeles i fadet over løgene.
Laksen placeres ovenpå grøntsagerne.
Panden koges af med vin og pernod, og det hældes over laks og grøntsager.
Det hele får ca. 20 minutter, eller til laksen er færdig, ved 200 grader.

Serveres med ris.

Jeg bestilte et navn til retten, men fik ikke rigtig noget. Så nu hedder det "Lax på grønt"


Ting fra weekendavisen

https://www.weekendavisen.dk/kultur/pasta-a-la-tiktok
https://www.weekendavisen.dk/kultur/spis-paris
https://www.weekendavisen.dk/kultur/maizena-alkymi
https://www.weekendavisen.dk/kultur/kunsten-at-klare-kikaerterne
https://www.weekendavisen.dk/kultur/saucernes-laerling
https://www.weekendavisen.dk/kultur/sodavand
https://www.weekendavisen.dk/kultur/aeggekogeriet
https://www.weekendavisen.dk/kultur/ben-med-et-hul
https://www.weekendavisen.dk/kultur/honninghjertets-forbandelse
https://www.weekendavisen.dk/kultur/creme
