# Drinks

## Pet Shop Boys inspireret

fra the royal opeara house i anledning af psbs koncerter i juli 2024
med barens kommentarer.

### It's a sin
Cherry+vivir tequila + cbd highball

Combining some controversial ingredients to match with a song about guilt
and repression stemming from a strict religious upbringing.

### Go West
Blueberry & vanillia moscow mule wit east london liquor vodka

A fruity sweet take on a moscow mule from song themed on a soviet pursuit
of freedom, hope and a better life

### West end girls
Peach & almond mojito with east london liquor rum

Varying flavours combine in a song about the contrasts and challenges of urban life,
exploring themes of social class and existential angst in the city.

### What have I Done to Deserve this?
Burnt Faith English brandy, apple & caramel fizz

A soothing, comforting cocktail for a song about the emotional struggle and confusion
following a relationship breakup.

### Always on my mind
Basil & Di Capri Limoncello Tom Collins with Portobello gin.

Zingy and herby expression on a classic cocktail and modern classic song
about regret and longing for not showin enough appreciation to a loved one.