# Det grønne

## Svampe og safran risotto

Generelt bruger vi 4 dl risotto ris når der laves risotto. 
120 gram passer også fint i denne opskrift.

* 25 gram røget svampe garum - eller svampe bouillon
* 200 gram svampe - skåret i skiver
* 15 gram olivenolie
* 15 gram smør
* 1 lille løg
* 120 gram arborio ris
* 10-15 tråde saffran
* 600 ml vand
* 2 håndfulde revet parmasanost

Karameliser svampene i olie.
Tilsæt smør og 5 gram garum.

Klar løg i olie
Tilføj ris, lad dem blive dækket i olie og giv dem lidt varme.

Bland resten af garumen og vandet, hæld 400 ml over risene, og 
tilsæt også safronen.

rør konstant til væsken er absorberet. Tilføj resten af 
væsken, undervejs - til risen er færidg.

Rør en håndfuld parmasan i - tilføj lidt mere væske, og 
resten af osten. Smag til og juster konsistens med væsken.

Tag af varmen, rør svampene i, giv den lidt persille eller lignende
grønt på toppen, og server. 


## chachouka

* 5 peberfrugter (men det afhænger selvfølgelig af størrelsen) er passende.
* 6 æg er fint.
* løg
* spidskommen
* paprika (lad nu være med at komme det i fra starten)
* safran
* en dåse hakkede tomater
* salt og peber
* Hvidløg


## Dahl

* 210 gram røde linser
* 2 spsk revet ingefær
* 4 finthakkede hvidløg
* 3 tsk karry (medium stærk)
* 1 spsk spidskommen
* 0,50 spsk stødt koriander
* 0,50 tsk stødt kardemomme
* 0,50 tsk chiliflager
* 6 dl grøntsagsbouillon
* 200 g røde linser
* 2 dåser hakkede tomater
* 2 spsk olivenolie


## Søren Davidsens Tomatsuppe

Som egentlig er fra The Guardian.
Men så dør referencen til What We do in the shadows...

Suppen:

* 2 auberginer (hvis de er små. 550 gram)
* 350 gram cherry tomater
* 2 store røde chilier
* 100 ml olivenolie
* 2½ spsk tomatpasta
* salt og peber
* 1 liter kyllinge fond
* 1 spsk lemon juice
* Brød croutoner.
* Frisk oregano og persille. Man kan godt klare sig med frossen persille.

Aiolien

* 5 fed hvidløg - finthakket (meget)
* 8 ansjoser (fileter) - finthakket (meget)
* 90 ml olivenolie
* 50 ml solsikkeolie
* 1 æggeblomme
* 1 spsk lemon juice

Hæld hvidløg, ansjoser og olivenolie i en gryde. Det er stærkt fristende at tage
en lille kasserolle. Brug i stedet en der er stor nok til
den samlede mængde suppe, det sparer på opvasken.

Lad det simre ved middel varme i 12 minutter. Pas på at hvidløgene ikke brænder.
Tag af varmen, og flyt 60 gram af blandingen over i en beholder - tilsæt solsikkeolien.

Lad det nu få samme temperatur som juice og æggeblommen.

Skyl tomaterne, flæk chilierne og fjern det hvide og frøene. Hak chilierne
groft.
Skyl auberginerne. Skræl dem i striber - tænk zebra. Men sørg for at den skræl
der er tilbage på auberginerne er ret tynd - det kan være lidt træls at tygge i
ellers. Skær dem ud i 3 cm tykke skiver. Vend grøntsagerne i olien, giv det en
tsk salt, og rigeligt med peber. Og så skal det i ovnen i en lille bradepande
ved 210 grader varmluft i 45 minutter. Vend det hele ca. halvvejs.

Resten af hvidløg/ansjos/olie blandingen fra før får nu varme, og tomatpureen/pastaen
varmes igennem i ca. 4 minutter. Tilsæt fond og juice. Og en kvar tsk salt.
Lad det simre i 15 minutter ved middel varme.

Nu rører vi æggeblommen sammen med 1/8 tsk salt og juicen. Og rører derefter
en mayonaise med den olie vi tog fra tidligere (og blandede med mere olie).
Lad dig ikke friste af den oprindelige opskrift der foreskriver en foodprocessor.
Håndkraft og et gammeldags piskeris fra Raadvad er vejen frem her!

De stegte grøntsager fordeles i fire skåle,
suppen fordeles i samme skåle. Kroutoner drysses over, en solid klat aioli oven i.
Drys med krydderurterne og et par vrid peber. Server straks.

Eller placer grøntsagerne i et lille fad, og sæt gryden på bordet sammen med
kroutoner og aioli, hvis det ikke behøver at være meget fornemt og fancy.

# Snyde-morgenmads-tærte

Eller - til frokost. Den går også fint til aftensmaden.

200 gram svampe
200 gram frisk spinat- renset
275 gram butterdej fra supermarkedet
1 spsk mascarpone
1 håndfuld friskrevet parmasan
1 spsk røget svampe garum
4 æg

Tænd ovnen på 180 grader c.
Flå svampene fra hinanden og læg dem i en bradepande med 
bagepapir. Sæt den i ovnen mens den forvarmer, så de 
tørres en smule.

Spinat i skål, overhæld med kogende vand. Sigt vandet fra så
snart spinaten har været dækket med vand.

Tryk vandet af spinaten - så snart det er koldt nok til at 
du kan håndtere det. Nej, der er ikke meget tilbage.

Når svampene har været i ovnen ca. 10 minutter, tages de ud
og hældes i skål. Tilføj garummen og slyng svampene rundt i det.

Tilføj spinaten, hvor du trækker bladene ud fra den klump du
fik ud af at trykke vandet fra. 

balnd godt med hænderne. Tilføj mascarpone og ost og fold det
sammen.

Tag butterdejen fra køleskabet og placer det på en bageplade.
Bare lad bagepapiret fra butterdejen blive på.
Smid svampe/spinat/oste blandingen på butterdejen. Brug en
ske til at lave fire små fordybning. Slå de fire æg ud i 
fordybningerne.

Fold hjørnerne af butterdejen ind mod midten af tærten. Trim
evt lidt af bagepapiret af med en saks. Pensl dejen
med et pisket æg eller mælk, og bag i 20 minutter. 


## Dahl
Eller Daal. En indisk klassiker. Linser lyder utroligt kedeligt og trist, ja nærmest vegansk. Og det kan det også godt være. I min udgave kommer der dog pølser i. For vegetarer er noget vi tilbereder og spiser her i huset.

2 spsk olivenolie
4 finthakkede hvidløg
2 tsk stødt ingefær
3 tsk karry
1 spsk stødt spidskommen
½ spsk stødt koriander
½ tsk stødt kardemomme
½ tsk chiliflager (eller bare chilipulver)
6 dl grøntsagsbouillon. (6 dl vand og en bouillonterning)
200 gram røde linser
2 dåser hakkede tomater
1 chorizopølse

Varm olien op i en stor gryde - gerne af støbejern - ved middel varme. Tilsæt hvidløg og rør rundt i 1 minut. Pas på det ikke bliver brunt. Tilsæt krydderierne og lad dem stege med et minuts tid.

Skyl linserne i en sigte - eller et dørslag hvis huller i det er små nok, og tilsæt dem til gryden, sammen med resten af ingredienserne - undtagen pølsen.

Lad det simre under låg i 45 minutter.

Pil skindet af pølsen og skær den i mundrette bidder. Lad den koge med de sidste 10 minutter. Lidt afhængig af hvor stærkt den er krydret. Og hvor krydret du vil have din dahl. Smag til med slat og peber.

Og så bør man selvfølgelig spise den med raita (det indiske svar på tzatziki) og hjemmebagte naanbrød.

Det bliver nu oftere bare med ris.


## Glaserede gulerødder

Hyppigt frembragt i køkkenet. For vi skal have nogen grønsager, og skamkogte gulerødder fik vi nok af som børn. Men det bliver hurtigt for kedeligt hvis det bare er gulerødder vendt i honning. Derfor:

1 kg gulerødder
8 spsk smør
1 dl bourbon eller whiskey
1½ dl brun sukker. Farin eller muscovado.
½ tsk salt
1/4 tsk sort peber
1/4 tsk cayenne peber
Skræl gulerødderne, og skær dem i skiver.
Steg dem på meget varm pande i et minuts tid i 1 spsk smør. Gerne af to omgange, afhængig af hvor stor din pande er.
Tag gulerødderne af panden, og hæld whiskey på. Pas på, panden er varm, så det kan godt give ret kraftige alkoholtåger i køkkenet. Lad det koge et halvt minuts tid. Sænk varmen og tilsæt resten af smørret.
Tilsæt sukker, og lad det smelte ind i smørret. Nu kommer gulerødderne tilbage på panden og røres godt ind i sovsen. Når det hele bobler, får det lov at hygge sig 5-6 minutter under låg.
Smag til med salt, peber og cayennepeber. Lad det koge - uden låg - 5-7 minutter ekstra. Eller til du synes at glaseringen har den tykkelse du godt vil have.


## Gulerødder med ingefær

Gulerødder er sundt. Og vi spiser for få grøntsager. Så:

* 5-6 gulerødder - afhængig af sult og størrelse.
* En stump frisk ingefær
* 1 økocitron
* Salt, peber og olivenolie

Skræl gulerødderne, og stiml dem med skrælleren, så du får en lang, flad strimmel. Fortsæt til der ikke er mere gulerod tilbage. Der skulle nu være en bunke tynde gulerodsstrimler op køkkenbordet.

Riv lidt frisk ingefær. 5-6 riv afhængig af hvor godt du kan lide ingefær. Pres citronen.

Varm olivenolien op, steg gulerodsstrimlerne et halvt minuts tid under omrøring.

Tilsæt ingefær og citronsaft. Og giv den et par riv af citronskallen i tilgift. Steg videre ca 3 minutter. Smag til med salt og peber. Husk, grøntsager behøver ikke været gennemkogte - der må godt være lidt bid i dem.

## Pestokartofler

En slags pesto i hvert fald.

Svigerinden gør ikke så meget i madlavning (den ene af dem - den anden gør). Men når hun gør, er det faktisk slet ikke så ringe endda. På jydsk, hvilket er passende.

Til den yngste af de jydske yndlingsniecers fødselsdag havde hun lavet nogle pestokartofler der fik mig til at spørge efter opskriften. Det er ikke en traditionel italiensk pesto, der laves på pinjekerner, men stadig pesto.




* 75 g ristede mandler (giv dem en tur på panden. De skal ikke smuttes)
* 1 kg kartofler
* 2 dl olivenolie
* 1 potte basilikum
* 75 g parmesanost (riv den selv. Forrevet parmasan lugter af bræk)
* 2 fed hvidløg
* salt og peber

Smid alt andet end kartoflerne i blenderen og blend til det er en fin ensartet masse.

Skræl kartoflerne, skær dem i både, og vend dem i pestoen.

Bag kartoflerne ved 200 grader i 40 minutter. Tada!


## Kartoffelkuber

Lyder mere fantastisk end det er.

På den anden side ser det faktisk ok ud, og smager godt. Så mit forbehold handler vel mest om at det er superenkelt.

En bagekartoffel skæres ud i tern, 4-5 cm på hver kant. Det her er noget der bør laves i kombination med noget kartoffelmos, pure,  suppe eller andet. For der er et enormt spild.

Vend kartoflerne i neutral olie, med salt og peber. Ham der gav mit tippet til det her hælder karry i, selv har jeg brugt paprika. Det gør ingen forskel efter min mening, al smagen i krydderiet bliver brændt af alligevel.

Varm ovnen op til 230 grader, hæld kartoflerne i et fad, og bag dem i 30 minutter.

Skru varmen ned til 150 grader, og bag videre i 10-15 minutter.

Vupti!


## Rødløgsalat

Man kan ofte have behov for en hurtig lille side ting til maden. Her en superenkel lille ting.

Rødløg - snittet i tynde ringe.
Vendt med hakket persille og sumak

Jeg aner ikke hvad det hedder, men det er ret godt, gerne til stegt kød. Og oplevet i Grækenland, uden at jeg ved noget om hvor græsk det egentlig er.


## Tomatsalat

Efter en opskrift svigermor har fundet et eller andet sted.

* 1 kg små tomater. Gerne nogle orange imellem.
* 4 spsk groft salt
* 1 bundt hakket basilikum. Eller koriander. Eller en blanding.
* 3 fed hvidløg. Finthakket.
* 1 spsk oregano
* 5 spsk god balsamico eddike
* 1 dl olivenolie
* 1 tsk sukker
* Salt og peber (men nok mest peber)

Skær tomaterne i grove stykker. Bruger du forskellige tomater, så har de formentlig forskelig størrelse, og så skærer du dem så de har ca. samme størrelse. Brug gerne de små cherry tomater, san marzane (eller hvad de nu hedder), små blommetomater.

Vend tomaterne med salt, og lad dem stå i et dørslag og dryppe af i 1½ time.

Krydderurter, hvidløg olie og eddike, sukker og peber blandes til en dressing. Når tomaterne har trukket samles tomater og marinade i en skål, og træk et par timer. Smag til med salt. Og server.


## Kålrabisovs

Hvad stiller man op med sådan en fætter?

Skær et par kålrabier i  små tern.
Snit et par hvidløg fint.
Smid begge dele i en tykbundet kasserolle - uden fedtstof, for de skal 
ristes let, uden at hvidløget tager farve!
Når de er ved at være møre, men stadig har godt bid, tilsættes fløde og ret store
mængder finthakket persille. Kog til fløden tykner lidt. Smag til med salt og 
peber. God til lam.

## Kartoffelgratin

Fra house of small wonders - skal nok modificeres før publikation

En del endda. Prøv at starte med at gøre noget ved kartoffelsorten.

20 g smør

1 kg kartofler, skrællet og i mindre, mundrette stykker

2 fed hvidløg hakket

420 ml mælk

420 ml fløde

1 tsk salt

½ tsk stødt muskat

1/4 tsk sort peber (stødt)

1/4 tsk cumin

70 g revet emmentaler

40 gram revet parmasan

varm ovnen op til 180 grader

smelt smør i gryde, tilføj kartofler og hvidløg og rør rundt til kartoflerne er dækket af smør

tilføj mælk, fløde, salt og krydderier, bring i kog og lad simre til kartoflerne er møre.

Hæld blandingen i form, drys osten over, og bag i 20-25 minutter, til overfladen er gylden. Drys gerne med persille.

## Bønner

Vi gør ikke så meget i bønner. Altså bortset fra de grønne. Andre slags bønner har en tilbøjelighed til at komme fra dåse. De er ret kedelige. Og derfor indgår de kun i kosten hjemme i nørdborgen når der laves chili.

Men det er jo fjollet og på efterårets tur til Firenze, besøgte vi en restaurant med en dækmand i døren. Og nogle guddommelige bønner. Resten af menuen var også fantastisk. Men bønnerne! De var svaret på mine bønne-bønner.


    1 pound dried Cannellini or Great Northern Beans
    fresh water
    2 Tbs. olive oil
    1 large sage sprig
    3 unpeeled cloves of garlic
    Terra Cotta Bean Pot & Flame Tamer or Enamel Cast Iron Pot
    Salt
    Extra Virgin Olive Oil
    Sage sprigs for garnish


    The day before you plan to cook the beans, place them in a strainer and rinse well with cool water. Check the beans for particles and remove any extraneous material. Put the rinsed beens into either the Bean Pot or Enamel Cast Iron Pot and cover with 2 inches of fresh water. The beans should be soaked overnight.
    The next day pour out the soaked beans in a strainer and rinse well with fresh running water; the beans will have doubled in size. Place the beans back into the cooking vessel, if using a terra cotta pot place the flame tamer on the heating element first. Cover the beans with 2 inches of fresh cool water; add the sage sprig, garlic cloves and olive oil to the pot and slowly bring the pot to a gentle boil. Simmer the beans gently until tender - if using the terra cotta bean pot this can take between 2 to 3 hours, if using an enamel cast iron pot the time should between 45 to 60 minutes. Once the beans are tender, remove the pot from the heat and set aside.
    At the time of serving, reheat the beans gently and season with salt. Place into serving bowl and season with Extra Virgin Olive Oil and garnish with sage.


## Gratineret kålrabi
Vi fortsætter kålrabi temaet.

Skær en håndfuld kålrabi i store tern
Vend dem med lidt bacontern, hakket persille, salt, peber og finthakket hvidløg i en dyb gratinskål.
Overhæld med fløde og revet ost.
Smid i ovnen ved 200 grader til det virker mørt og osten har taget farve.

Det virker også med andre grøntsager man ellers ikke aner hvad man skal gøre med.
