# Gris

## Bacon medisterpølse i airfryer
Medisterpølse vikles ind i bacon.

30 minutter i airfryer ved 180 grader.

## Behåret Biker pølse

Som man si'r

Eller Hairy Bikers' sausage casserole


- 1–2 spsk solsikkeolie
- 12 grisepølser - i god kvalitet
- 6 tykke skiver bacon - skåret i lardoner af ca 2.5 cm.
- 2 løg, skåret tyndt
- 2 fed hvidløg - smadret
- ½–1 tsp hot chilli powder or smoked paprika
- 400g hakket dåsetomat
- 300ml kyllingefond
- 2 spsk tomatpure
- 1 spsk Worcestershire sauce
- 1 spsk mørk muscovado sukker
- 1 tsk diverse tørrede krydderurter. Salvie, oregano. Den slags.
- 2 laurbærblade
- 3–4 stilke frisk timian
- 100ml rødvin
- 400g bønner fra dåse. Skyllet
- salt og peber
- Ris eller groft brød. Eller begge dele

Varm 1 spsk olie i en pande, og steg pølserne (nænsomt) i 10 minutter. Vend dem undervejs, til de har fået jævn farve.
Flyt dem over i en gryde.

Steg bacon i panden til det begynder at bliver brunt og sprødt. Over i gryden til pølserne.

Steg løg i ca 5 minutter i panden ved medium varme til de er klare. Der burde være baconfedt nok, men giv evt lidt mere olie. Tilføj hvidløg og giv dem 2-3 minutter sammen med løgene, til de (løgene) bliver lysebrune.

Drys chili over og giv dem et par sekunder længere.

Rør tomater, fond, tomatpure, woostersovsen, sukker vin og krydderurter i. Varm op til det simrer.

Tomatblandingen over i gryden og bring den op til at simre. Skru ned for varmen, og lad det hele stå og putre i 20 minutter. Rør undervejs.

Rør bønnerne, og lad det simre videre i 10 minutter. Rør undervejs, og lad sovsen tykne.

Smag til med salt og peber og server med ris eller groft brød.

## Svinemørbrad med dijonsennep og porrer

- 1 stor svinemørbrad, eller to mindre
- 1 løg
- 2 porrer
- 4-5 fed hvidløg
- 1 spsk mel
- 1 glas hvidvin
- 4 dl hønsebouillon
- 2 spsk dijon sennep
- 2 spsk grov dijon sennep (a l'ancienne)
- 1 spsk smør
- lidt olivenolie
- 2-3 dl creme fraiche
- salt og peber, evt lidt sukker

Hak løg og hvidløg fint. 

Rens porrerne, flæk dem og skær dem i tynde skiver.

Puds svinet af, krydr med salt og pber, brug i stegegryde med olie.

Tag den op. Smør i gryden, løg, og porrer. Lad dem sautere til det er blødt og faldet sammen.

Drys melet i gryden og lad det bage af under omrøring. Vin i - kog op. Bouillon i, bland godt, og kog op. 

Svin kommes tilbage i gryden og simrer færdig under låg og svagt blus. 15-20 minutter afhængig 
af svinets størrelse. 

Pil svinet op igen, og hold den varm under folie. 

Smid creme fraiche og sennep i og kog igennem igen-igen. Smag til med salt, peber og evt. sukker. 

Svinet kommes tilbage i gryden igen-igen-igen, og varmes igennem. 

Så piller vi dyret op igen, og skærer det i ikke alt for tynde skiver, server dem med 
kartoffelmos, ris eller for den sags skyld pasta, garneret med sovsen, og evt lidt helt tynde porreringe hvis Pyntejørgen kommer forbi.

## Trykkoger risotto

Svine elementet er bacon.

Vi har en trykkoger. Men den bliver ikke brugt så ofte. Det bør der laves om på, for hele konceptet i trykkogeren er at ting går hurtigt. Og det har jeg ofte brug for, når alt det andet skal nås.

Min husbond har en hobby, hvor han finder eksotiske opskrifter til mig på nettet. Det holder mig beskæftiget i køkkenet, så jeg ikke brokker mig over al den tid der bliver brugt på World of Warcraft. Ren win-win!

Og en af de opskrifter han fandt, handlede om risotto i trykkoger. Så det prøver vi:

- 700 gram champignon
- 950 ml kyllingefond
- 300 gram risottoris
- 3 små løg. Sådan ca. 150 gram i alt. Hakket.
- 2 fed hvidløg, finthakket
* 1 pakke bacon, skåret i tern.
* 1½ dl hvidvin
* Smør, olie, salt, peber og parmasan

Baconen blev stegt i trykkogeren. Champignonerne blev renset, skivet og stegt med baconen. Der blev tilsat en spsk smør og en sjat olie, og svampene blev stegt til de først havde smidt vandet, og derefter optaget det igen. Giv dem et godt drys salt. Så kom løgene i, de blev stegt til de var klare. Hvidløgene blev tilsat og stegte med i et par minutter. Hvidvin hældt over, og kogt til det ikke duftede af alkohol længere.

Derefter kom risotto risene i. De stegte med til de begyndte at ligne små isterninger. Lidt gennemsigtige i hjørnerne. Endelig blev fonden hældt på, og trykkogeren lukket. Fuldt skrald på pladen.