# Kartoflerne


## Kartoffelfrikadeller

- 500 gram kartoffelmos
- 1 revet løg
- 1 æg
- 3-4 spsk hvedemel
- 4-5 spsk rasp
- salt og peber

Rør alt sammen, steg dem 2-3 minutter i olie/smør

Nappet fra Maden i mit liv siden. 



## Mississippi Mud Potatoes

Den ondeste comfort food
* 1½ kg kartofler - skrællet og skåret i mundrette tern (måske lidt større. De svinder)
- 2½ dl revet cheddar
- 3/4 kop majonæse
- 3 smadrede hvidløg
- 500 g bacon i tern - stegt
- ½ cup hakket løg

Forvarm ovnen til 170 grader. Sådan ca. Varmluft.
Fedt en bradepande
Smid alt i bradepanden - bland godt så alt er dækket.
Bag hele svineriet i 1½ time - eller til kartoflerne er møre.
Rør gerne undervejs.
Vupti. Overvej hvilken cheddar du bruger. Den billige fra 365 skiller 
fuldstændigt og der er intet gooey eller stretchy over det.

## Curly fries

Du kender dem godt. De der snoede fries du får på fastfood restauranten.

De laves selvfølgelig ikke ved at skære kartoflerne ud på den måde.

I stedet laves de af kartoffelmos.

- 500 gram kartoffelmos (evt rest)
- 1 æg
- 50 gram majsstivelse (også kendt som maizena)
- 30 gram revet parmasan (fintrevet)
- Salt og peber
- Neutral olie til stegning

Bland alle ingredienser (bortset fra olien) sammen, og hældt på sprøjtepose. Klip hul i bunden.

Varm olien op til ca. 170 grader (eller der hvor det syder om en tændstik), og sprøjt blandingen ud i olien. Der kan laves spiraler eller andre sjove former.

Friter dem til de er gyldne (og vend dem!). Drypper af på fedtsugende papir.


## Forskellige slags kartofler

Vi skal have kartofler til. Men jeg har fået så utroligt mange kogte kartofler i min barndom at jeg ikke orker at servere dem for nogen, endnu mindre at skulle spise dem. Så. En oversigt over standardkartofler. Så her er min liste over forskellige måder at tilberede kartofler.

Ingen opskrifter. De kommer måske. For de fleste skal der stå "pommes" foran.

- À la crème
- Allumette
- Anglaise
- Anna
- Au four
- Bonne Annè
- Bouillonkartofler
- Brunede kartofler
- Cannelure
Carrées
Château
Cocotte
Copeau
Croquette
Dauphine
Duchesse
Fermiere
Fondantes
Frites
Galettes
Gaufrettes
Gratin
Gratin (en minute)
Hash brown
Hasselback
Kartoffelmos
Kartoffelsouffle
Lorette
Lyonnaise
Macaire
Maître d'hôtel
Noisette
Paille
Parisiennes
Persillees
Pont-neuf
Purées
Faffles
Rissollees
Rösti
Saint-florentin
Sautees
Soufflees
Spirella

