# Ko

Ko-opskrifter.

## Boeuf saute stroganoff

Pricernes opskrift.

* 800 g oksefilet
* 3-4 spsk edelsuss paprika
* 3-4 løg
* 2 spsk smør
* 300 g champignon (eller andre svampe)
* 5-6 tykke skiver bacon
* 2 spsk tomatpure
* ½ l fløde
* salt og peber

Kødet skæres i strimler på størrelse med en lillefinger. Det pudres med
paprikaen. 
Svampene skæres i tynde skiver og steges i lidt smør. Fisk dem op og læg
dem til side.
Løgene hakkes og klares i mere smør. Når de er klarede fiske de op og lægges
til side.
Bacon skæres i mindre strimler og steges til de er gyldne - men ikke for
sprøde. Fisk også dem op.
I det fedt der er tilbage i gryden brunes kødstrimlerne over ret kraftig varme. Men pas på paprikaen brænder let på.

Tilsæt tomatpureen og steg den lidt på panden.

Alt det der var lagt til side kommes op i gryden
igen. Fløden hældes på, og der koges til det
tykner. Smag til med salt, peber og evt. lidt
mere paprika.

Pricerne ville servere fritter. Mos eller ris
er også glimrende.

## Stifatho

Det har sikkert været med ged eller lam snarere end ko. Men her i huset laves det med ko.
800 g oksetykkam eller lignedne
15 hele løg (lidt afhængig af deres størrelse)
4 fed hvidløg
5 laurbærblade
2 spsk tomatpure
4 dl rødvin
½ kalve eller okse boullion
olivenolie, salt og peber

Puds kødet af og skær det i store tern - 2-4 cm på hver led.
Steg det afpudsede af i en separat gryde, og hæld bouillion over - lad det 
simre.
Kødet brunes godt af i stegegryden, gerne af nogle omgange.
Pil løgene og smid dem i gyrden.
Pil hvidløgene og mos dem. De skal også i gryden.
Laurbærbladene kommer også i, og så lader vi det hele få varmen i gryden,
før vi steger tomatpureren af, og hælder rødvin på.
Sigt boullionen, og hæld den i gryden også. Salt og peber skal også i nu.

Skum af, lad simpre i 1½ til to timer (ikke meget længere, så bliver kødet 
tørt). Giv gerne løgene nogle tæsk undervejs, og jævn evt. til sidst.

Smag til med salt, peber og rødvin, hvis der er mere tilbage. Server med mos eller
ris.
