# Ko

Ko-opskrifter.


## Stifatho

Det har sikkert været med ged eller lam snarere end ko. Men her i huset laves det med ko.
800 g oksetykkam eller lignedne
15 hele løg (lidt afhængig af deres størrelse)
4 fed hvidløg
5 laurbærblade
2 spsk tomatpure
4 dl rødvin
½ kalve eller okse boullion
olivenolie, salt og peber

Puds kødet af og skær det i store tern - 2-4 cm på hver led.
Steg det afpudsede af i en separat gryde, og hæld bouillion over - lad det 
simre.
Kødet brunes godt af i stegegryden, gerne af nogle omgange.
Pil løgene og smid dem i gyrden.
Pil hvidløgene og mos dem. De skal også i gryden.
Laurbærbladene kommer også i, og så lader vi det hele få varmen i gryden,
før vi steger tomatpureren af, og hælder rødvin på.
Sigt boullionen, og hæld den i gryden også. Salt og peber skal også i nu.

Skum af, lad simpre i 1½ til to timer (ikke meget længere, så bliver kødet 
tørt). Giv gerne løgene nogle tæsk undervejs, og jævn evt. til sidst.

Smag til med salt, peber og rødvin, hvis der er mere tilbage. Server med mos eller
ris.