# Kondimenterne 

## Syltede rødbeder



## Syltede champignon
- 500 gram hvide champignons, (grundigt) rensede og rodskårne
- 2 dl mørk balsamico
- 2 dl olivenolie
- 1 spsk salt
- 20 sorte peberkorn
- 5-8 laurbærblade

Rør alt andet end svampene sammen - grundigt
Læg svampe i sterilt glas, hæld lage over, og lad trække i 
to døgn. Spises som tilbehør til grillet kød, som tapas elleer
i salater

## Trykkogerketchup

Efter www.hippressurecooking.com/pressure-cooker-ketchup-recipe
og Dansk Kemi 2020 (6) p. 38 - 39, ved Jens Folke

- 1 kg blommetomater skåret i kvarte
- 15 g paprika
- 5 g salt
- 1 g stødt kanel
- 1 g nelliker stødt
- 2 g hvidløgspulver
- 2 g sellerifrø
- 10 g dijonsennep
- 15 g honning
- 80 g  rosiner
- 1/4 zittauerløg
- 85 ml æbleeddikke
- 15 g majsstivelse rørt ud i 15 ml vand

Kan yderligere krydres med chili, røget paprika, æble, korianderfrø
m.m.m

Smid alt undtagen majsstivelse og vand i trykkogeren.

Mos tomaterne nok til at væsken når op på trykkogerens minimumsbehov
bring trykkogeren under tryk, når den når 2 atmosfærer, lad koge i
5 minutter
Tag trykket af, og lad det koge ind i 10 minutter det skal reducere til knap
halv mængde.

Bland majsstivelse i vand, og hæld det i - lad det koge med.

Smadr blandingen med stavblender - passer gennem sigte. 
 
## Skalottemarmelade

giver 1½ kop

- Neutral olie
- 1 kg skalotter - pillet og hakket
- 3/4 teske salt
- ½ kop sukker
- 6 spiseskeer malteddike - eller anden eddike.

Olie i sauterpande. 
Løg og salt i pande.
"kog" under låg i ca. ti minutter. Rør undervejs, til løgene er klare
skru ned for varmen og tag låget af.
tilsæt sukker og 1 spsk vand. simrer i 30 minutter. deglacer med 1 spsk vand efter behov.
rør derefter fire spsk eddike i. simrer videre i 10-15 minutter, til konsistensen er jammy.
rør den resterende eddike ind, og sluk for varmen.
Smag til.
Hæld på glas (skoldet etc)

## Fars nylon
Aka 1000 øers dressing

- Mayo - svarende til af en æggeblomme og 3 dl olie
- 1 spsk creme fraiche
- 1 spsk tomatpure
- 1 tsk engelsk sovs
- 1 knivsspids paprika
- 1 smule tabasco
- 1 smule cognac
- 1 smule sukker

Det hele blandes sammen.

## Worcestershire Sauce - Engelsk sovs

Eller hvad pokker det nu hedder...

- 500 ml Æble eddike
- 4 fed hvidløg
- 120 g skalotteløg
- 30 g ansjosfilleter
- 60 g honning
- 60 g rørsukker eller melasse
- 60 g tamarind paste
- 2 tsk chilipulver
- 1 tsk stødte nelliker

Alt smides i en gryde, og der stavblendes til det er så smooth som muligt.

varm op ved medium varme til den koger. Skrug ned til lav varme og lad simre
i 15 minutter under omrøring.

Herfra er der to metoder:

1. Filtrer gennem kaffefilter. Lad det dræne en times tid. Rør let i pastaen 
så det meste kommer igennem. (brug evt først det fine nylonfilter).

Tilsæt tre tsk af filterkagen til filtratet, ryst grundigt og hæld straks på 
rengjorte skoldede (evt atamonskyllede) flasker. Opbevar mørkt og køligt 
(men ikke i køleskabet). Lad den lagre mindst 2 måneder, helst 18 måneder.

Filterkagen kan med fordel gemmes og tilsættes supper, gryderetter eller andet godt.

2. Hæld sovsen direkte på rengjorte, skoldede, evt. atamonskyllede flasker.
Den lagres ligeså længe. Der er frit valg ang. filtrering efter den har lagret.


## WHISKEY BACON JAM
- ½ kg bacon - i tern
- 2 store løg, tyndt skåret
- 3 cloves garlic, minced
- ¼ cup brown sugar
- 3 tbsp whiskey or bourbon
- 2 tbsp maple syrup
- 2 tbsp balsamic vinegar
- 1 tsp black pepper
- ¼ tsp cayenne pepper
- ¼ cup water


1. Tilbered bacon i stor gryde over medium varme - til det er sprødt.
2. Tag baconen op og efterlad i hvert fald 2 spsk baconfedt i gryden.
3. Tilsæt løg og tilbered ved mediumvarme til de er karameliserede. Tag dig god tid - 20-25 minutter.
4. Tilsæt hvidløg og steg med et minuts tid.
5. Smid baconen tilbage i gryden og tilsæt sukker, whiskey, ahornsirup, balsamico og krydderierne.
6. Add water and simmer until mixture thickens, about 10-15 minutes.
7. Let cool slightly, then pulse in food processor to desired consistency.
8. Allow to cool completely before transferring to jars.
9. Perfect for burgers, grilled cheese sandwiches, crackers with cheese, or roasted meats.
10. Store in refrigerator for up to 2 weeks.
 
 
 
## Ketchup

En af basisfødevarerne. Beauvais smager af tysk rasteplads.
Heinz er bedst. Men er et amerikansk mærke, og vi er ikke fans af 
lande der styres af psykotiske bavianer med et ketaminmisbrug.

Så hvorfor ikke lave det selv?

- 1 løg
- 3 fed hvidløg
- 1 (mad)æble
- 1 kg tomater
- ½ frisk, rød, mild chili
- Olivenolie
- 2 spsk tomatpure
- 2 dl vand
- 2 spsk sukker
- 3 spsk eddike
- Salt og peber

Pil løg og hvidløg, skyl og skræl æblerne, skyl tomaterne.

Rens chilien, fjern især frøene!

Skær alt i grove tern. Det skal blendes, så det er ok at være doven. Steg (hvid)løg i en gyde i 3-4 minutter i en sjat olie

Tilsæt æbler, tomater, tomatpure og vand, og lad det hele simre i 10-15 minutter under låg. Blend det godt igennem, og smag til med sukker, eddike, salt, peber og evt cayennepeber.

## Havtorn sirup

- 4 dl havtorn.
- 4 dl sukker
- 3 dl vand.
- En stjerneanis

Det hele samles i en gryde, bring i kog og opløs sukkeret.
Kog dernæst i 5 minutter. 
Tag gryden af varmen og lad det trække i en times tid inden det filtreres - gerne gennem noget klæde. 
Kog yderligere ind til det har den ønskede konsistens
Hæld på atamon-skyllet flaske.


## Så er det syltetid – abrikoser og mandler

Hvordan resultatet bliver aner jeg ikke. For gryden er stadig på blusset.

- 94 g smuttede hele mandler
- 218 g halverede soltørrede abrikoser
- Korn af 1 vanillestang. De to halvdele kommer med i sylteglasset
- 15 ml amaretto
- 2,5 dl rørsukker
- 2,5 dl vand
- Et lille nip chilipulver

Det hele smides i en kasserolle, og koger op. Når det er oppe at koge, lader jeg det koge videre til temperaturen når 107 grader. Det skulle give en relativt tyk sirup. Når jeg har postet dette, skolder jeg et ½ liters sylteglas, og skyller det i en hættefuld atamon. Atamonen ryger i vasken bagefter, men glasset bliver ikke rystet for voldsomt, der må godt være et par dråber tilbage i glasset, af hensyn til holdbarheden.


## Syltetid III – Hasselnødder i lidt lakrids

Vi fortsætter – kæresten er nemlig til kor, så der er ikke så meget andet at tage sig til 

Det var en stor pose hasselnødder, og de endte ikke alle blandt fignerne i går. Så derfor:

- Hasselnødder nok til at fylde (næste) et ½ liters sylteglas
- 2½ dl rørsukker
- 2½ dl vand
- 1 tsk lakridspulver

Koges op, og ind, til temperaturen er 107 grader. Hældes på skoldet og atamon-skyllet glas. HSKDV. Og at dømme efter første smagsprøve, er lakridsen perfekt doseret.


## Syltetid IV – Figner og rødvin

Og søreme om ikke vi fortsatte – det er utroligt hvad man kan klare mens man taler i telefon med sin mor, bare man har et headset.

- 305 g tørrede figner
- 2½ dl rørsukker
- 1 dl rødvin (en barbaresco i dette tilfælde – det hvad hvad jeg alligevel havde trukket op)
- 1½ dl vand

Og nu skulle rutinen være på plads. Koge op – relativt roligt – til 107 grader, på skoldede og atamonskyllede glas. En hurtig prøvesmagning gjorde at den fik et lille skvæt ekstra rødvin fra glasset, så måske er det 1,25 dl rødvin den skal have i stedet. Og tag det nu roligt hvis det ikke er præcist 305 gram figner. 300 gram er sikkert ok, det var bare hvad der passede i mit ½ liters sylteglas.

## Syltetid – figner og hasselnødder

To portioner på en dag – men så har vi heller ikke flere sylteglas, så nu stopper det.

Det krævede en længere debat med kæresten, under brug af boolske operatorer og whiteboardtavle. Men til sidst endte det med figner og hasselnødder.

- 216 g tørrede figner
- 77 g hasselnødder
- 2 kanelstænger
- 2½ dl rørsukker
- 2½ dl vand
- 20 ml Morgan rom

Igen, hele svineriet i kasserollen, op med varmen (i moderat tempo, kanelstængerne skal have lidt tid til at trække), og koge ind til temperaturen når 107 grader. Skoldet glas skyllet i atamon. Så ser vi om det også passer med ½ liter denne gang.
