# Retter med kylling

## Kyllingetærte

* 1 kylling
* 2 løg
* 5 fed hvidløg
* 3 porrer (to rækker)
* 4 gulerødder
* 4 stilke bladselleri, som vi udelader fordi Kristian ikke er fan af selleri.
* 1 pastinak eller persillerod. Stor.
* 1/4 kg champignons.
* evt en håndfuld tørrede svampe. Ikke morkler eller den slags. Karl johan eksempelvis.
* Timian
* Laurbærblade 4 stk
* ½ liter kraftig hønsefond
* 2 spsk mel - toppet
* 1 glas hvidvin (2½ dl)
* 2 dl fløde
* Smør
* Olivenolie
* Butterdej

Fjern rygbenet fra kyllingen med en fjerkræsaks. skær brystbenet frit og ud.
krydr med salt og peber invendigt, og læg dyret på en rist med kødsiden opad.
Smør olivenolie på skindet og drys med sat. Bag den i ovnen ved 200 grad i 
45 minutter. Det går fint i en airfryer.
Ryg og brystben simrer i onden under låg i en halv times tid så vi får den 
smag med. Fisk ben op og tilsæt de tørrede svampe til fonden. Lad dem trække
en 20 minutters tid.
Hak løg - ikke for fint. Hak hvidløg - noget finere. Skær rodfrugterne, porrene
og sellerien (hvis du tager den med) i mundrette stykker. Rens svampene og 
halver eller kvart dem. 
Olie og smør i en stegegryde - når det er bruset af, først løg, lidt senere
hvidløg, og steg til de falder sammen, de skal ikke være helt karameliserede.
grøntsager og svampe tilsættes, sammen med timian og laurbærbladene. Steg det hele
til de tager en smule farve og rodfrugterner er en smule møre. Drys mel over
og bag af. Tilsæt fond og hvidvin lidt af gangen og kog til det tykner.
Tilsæt fløde og lad det simre yderligere et par minutter. Der kan jævnes lidt
mere med maizena. Det skal være ret tykt.

Når dyret er færdig i ovnen tages det ud og køler nok af til at man kan arbejde
med det. Evt. sprødt skind tages af og skæres i små stykker.
Al snask fra bradepanden skrabes over i gryden. 
Pil kødet fra dyret, og sær i mindre tern. Kom det i stuvningen og smag til med
salt og peber. Fisk laurbærblade og timianstilke (hvis du brugte frisk timian)
op. Smid også kyllingeskindet i.

Kom stuvningen i dyb tærteform eller lignede og lad det køle af.
Rul butterdej ud (hvis ikke den kommmer i plade). Pensl kanten på formen med æg
og læg butterdej på som låg. Pensl låget med æg, og skær et snit i midten af 
låget, så damp kan slippe ud. Bag i ca 35 minutter ved 200 grader. Lad 
den hvile ti minutter inden servering.


## Hverdagskylling med kremede svampe

Fra food52

* ½ kg svampe
* 4 spsk smør
* ½ kg kyllingebryster - Oprindeligt var det 1 kg
* 2½ dl piskefløde (eller madlavningsfløde)
* 2 spsk dijon sennep
* finthakket purløg

Rens svampene, skær halvdelen i skiver, og resten i kvarter.

* Smelt 2 spsk smør, 
* tilføj svampene, steg dem 10-15 minutter, til
de begynder at karamelisere. 
* Halver kyllingebrysterne på langs,
og bank dem med kødhammeren, ca 1/4 tomme så - 40 millimeter?
* dub dem af, og krydr med salt og peber.
* Giv svampene lidt salt og peber, deglacer med 1/3 cup vand.
* Smelt resten af smørret, steg kyllingerne. Smid gerne en 
bøfpresse ovenpå dem.
* Bland fløde og sennep. Rør dem i svampene, og kog under omrøring
til den tykner. Smag til med salt, peber og sennep.
* Saml - kylling overhældes med svamep. Vi serverer med ris.

## Onepot chicken & rice
Fra noma

* 60 g olie
* 4 kyllige lår uden ben, med skind
* salt
* 140 gram løg finthakket
* 3 fed hvidløg smadret
* 15 g tomatpasta
* 60 g hvid miso
* 15 g røget paprika

* 80 g røget svampe garum
* 600 g grøntsagsbouillon

* 10 g salt
* 200 g ris
* 10 g persille
* 200 g mayonaise
* 1 fed hvidløg - revet.

sautepande - olie varmes op unmder middel varme. krydr kyllingerne med generøse mængder 
salt. Når olien simrer, brunes kyllingen. til den er mørkebrun og sprød. ca. 4 minutter.
fjern kyllingerne fra panden. Skru ned til lav varme.
tilsæt løg og hvidløg. Steg til løgene er klare.
rør tomatpastaen i og steg ca. 5 minutter til tingene er rustent brune.
Tilsæt bouillon, salt, røget svampe garum, parpirka og miso. Øg temperatren til høj. Rør for at 
blande.

Når væsken koger, tilsæt risene og rør så de er jævnt fordelt. Her fra skal risene ikke røres!

Skru ned for varmen, og lad den simre. tilføj kyllingerne til gryden, med den rå side ned. (så ved stegningen
er det kun på skindsiden at den skal steges!) Når duften af brændte ris kan mærkes - efter ca. 20-25 minutter
er vi ca. færdige. tag af varmen, og lad hivle i 5 minutter. pynt med hakket persille.

Bland mayo med hvidløg og bland godt. 

Server portioner af ris på tallerken - husk at få det sprøde let brændte lag med. Kylling på toppen.
Top yderligere med hvidløgsmayo.




## Pollo orzo
One pot. Og relativt hurtig.

Orzo er de der små rislignende pastating. 

* Kyllingestykker. Helst med ben. En samling lår er fint.
* 3 fed hvidløg
* 2 tsk salt
* peber
* 1½ liter vand
* ~½ liter kyllingefond.
* En dåse hakkede tomater
* 1 løg eller to hvis det er et lille løg
* 340 gram orzo pasta
* persille

Brun killingerne i olie/smør/andefedt/margarine
ca. 5 minutter på hver side.

Tag killingerne op, og brun pastaen let i fedtstoffet.

Tilsæt finthakket løg og klar løgene. Smid finthakket hvidløg i til sidst.

Læg killingerne tilbage i panden.

Hæld fond og tomater over.

Låg på, og lad simre 10-15 minutter, afhængig af orzo type og killing.
Pastaen skal være al dente, killingen skal være gennemstegt/kogt.

Tag gryden af varmen, og lad den hvile i 5 minutter. Orzoen skal gerne absorbere
stort set al væden. Hvis det skal være ekstra festligt, så hæld persille over.