# Lam

## LAMMEKØLLE

Vi spiser ikke meget lam. Men til påske skal det være. Opskriften er oprindeligt fundet i Weekendavisen, men justeret undervejs – så jeg kan dårligt huske hvordan den oprindeligt var.

* 1 udbenet lammekølle
* 200 g gedeost
* 3 fed hvidløg
* 2 kviste rosmarin
* 20 tørrede abrikoser
* Kartofler – et par kilo
* En halv liter grøntsagsbouillon
* Salt og peber

Rosmarin – hakket, hvidløg – hakkede og abrikoserne – hakkede, blandes med osten.

Lammekøllen stoppes med mixet. Der er ikke plads til det hele – no worries.

Køllen snøres med bomuldstråd.

Kartoflerne skrælles eller skrubbes, skæres i både og fordeles i en bradepande. 

Resten af oste-blandingen fordeles blandt dem. Køllen placeres på en rist over kartoflerne, og hele herligheden får ca. 1½ time i ovnen ved 175 grader. 

Kernetemperaturen (i kødet – ikke i fyldet!) skal lande på ca. 60 grader. Rør gerne rundt i kartoflerne undervejs.

Bønner eller bønnesalat går godt hertil – det knækker lige den fede smag fra lammet og osten.