# Preservationerne

## Drunken Monkey Jam

- 3-4 store modne bananer
- saften fra 1 lime
- 1,25 dl sukker
- 1,25 dl brun sukker
- 1½ dl vand
- 1 tsk vanillepulver
- 1 tsk stødt kanel
- 2 spsk rom

Mas bananerne i en skål og hæld limesaft over.

I en gryde - opløs sukker i vand og bring i kog

Tilsæt bananer, vanille, kanel og rom

Skru ned for varmen og lad det simre i ca 30 minutter - smadr bananerne efterhånden som de bliver bløde.
    
Det hele skulle gerne blive ret tykt, og når det ikke længere er flydende, hælder du det på glas og sætter på
køl. Vær opmærksom på at det hele bliver tykkere når det køler af.


## Æblesmør

Den bedste måde at reducere groteske mængder æbler fra Svigermors have til relativt små mængder henkog.

- 2487 gram æbler, skrællet, og kernehus fjernet
- 1,2 l vand
- 3 stjerneanis
- vanillestang - eller vanillesukker
- 3 kanelstænger

Koges til mos.

Mosen paseres gennem sigte - vi skal af med stjerneanisen. 
Det er hård arbejde, så sæt god tid af.

Mosen over i en ren gryde/sauterpande eller lignende.
Kog sammen vanillestangen (eller sukkeret), samt kanelstængerne.
Simrer roligt under låg 1½ til 2 timer, til det bliver mørkt og tykt.