# Menuerne

## Confiteret and og pommes sarladaises

opr. udgivet 5. februar 2013

Kæresten har det hårdt i denne uge. Mest fordi jeg har det hårdt, med arbejdsdage der starter lidt over 7 og slutter lidt i 21. Der er kun tre dage tilbage i ugen, bortset fra dagen i dag, der trækker søm ud fordi chefen vil have lavet et stort og bøvlet 3D-print. Anyway, han har det ikke let, for hans kæreste står meget tidligt op, og kommer meget sent hjem. Og er ret slidt.
Så på lørdag, når ugen fra helvede er overstået, skal der soves længe. Og så skal der kræses lidt om ham.
Vi har haft en dåse konfiteret and stående et stykke tid. Jeg faldt over den i Inco, og nu skal den bruges. Anden selv skal bare graves ud af dåsen, og på panden en ti minutters tid ved meget høj varme.
Jeg håber at der er masser af fedt i dåsen. Det er nemlig en af de nemme måder at pifte kartofler op til et højere kulinarisk niveau. Steg dem i andefedt og hør ænderne synge.
Det bringer os til tilbehøret. Når nu vi står med store mængder andefedt, er det oplagt at lave pommes sarladaises. Det er også det de franske bistroer foretrækker at servere til konfiteret and.
Kartoflerne skrælles, og skæres i skiver. Sådan et par millimeter tykke. Det kan gøres i god tid, læg skiverne i vand i køleskabet. Så får man også det værste stivelse af dem.
Varm andefedtet op, og hæld kartoflerne i. De skal være tørre! Steg dem i gryden med 3/4 spsk salt, til de er dækket af fedt. Skru ned for temperaturen og steg dem færdig, indtil de er gyldne og møre. Det tager en 20-25 minutters tid. Vend kartoflerne regelmæssigt.
Skyl og hak et bundt persille, og knus to fed hvidløg. Rør persille og hvidløg i kartoflerne når de er færdige.
Server store mængder fransk rødvin, og måske en lille salat. Salaten er mest til pynt.

## 51 års fødselsdag 

20. juni 2025

Der er koncert dagen efter, så det skal være lidt afdæmpet, og restauranten må derfor vente til en anden dag.

Anyway, Knudsen går i køkkenet igen.

https://www.valdemarsro.dk/laksetatar/

Bøf, kartofler med bacon, parmasan og trøffel. Syndige kartofler
Ærter med grønne asparges.
Whiskey beurre blanc

Tarte tatin med pærer i stedet for æbler.
Og vanilleis.


## Blomsterbryllup

Så har vi været gift i fire år.

Dagen er præget af Corona-pandemien. Så vi sidder herhjemme. Dele af menuen er derfor knap så fancy som jeg ellers ville have skruet den sammen.

Forret:

Hummersuppe. Blot fra frost. Med ristet, hjemmebagt surbrødsdej. Og spædet op med en (meget) lille squeze piskefløde.

Hovedret:

Côte du Boeuf. Kartoffelkuber, morkelsovs og en let nedskaleret "den gode kones ærter". Som i: Ingen hjertesalat.

Dessert:

Crêpe Suzette med vanilleis. Hjemmelavet.

Hertil portugisisk hvid- og rødvin. Og hjemmelavet limoncello til desserten.

## Menu - til en månedsdag

Vi er håbløse. Ikke nødvendigvis håbløst romantiske. Men efter 7 år og 5 måneder; markerer vi stadig månedsdage. Det hjælper ikke at vi blev gift på en sådan. Så månedsdagen for hvornår vi officielt blev kærester, er søreme også månedsdagen for hvornår vi blev gift. Engang imellem tror jeg vores venner er lidt trætte af os. Deres koner og kærester får i hvert fald (nogle af dem) urealistiske forventninger til hvordan et parforhold skal fungere. Det er selvfølgelig fordi de kun ser opdateringer om hvordan vi forkæler hinanden den 30. i hver måned, og ingen om den løbende debat om hvor meget der bør støvsuges. Og ja, det er også et issue når det er to mænd der deles om støvsugeren...

Anyway, lige om lidt er det den 30. september. Der har vi været kærester i 7 år og 6 måneder. Og gift i 1 år og 5 måneder. Det må jo markeres.  Husbonden er til noget kortræning det meste af dagen, så jeg har god tid til at gå i køkkenet hele dagen, og forhåbentlig levere noget god mad når han kommer hjem.

Men hvad skal menuen så være?

Til forret:
Selleri-remoulade.

Jep. Husbonden bryder sig normalt overhovedet ikke om selleri. Men et par udgaver kan laves, uden at det er skilsmissegrund.

Selleri-remoulade prøvede vi i Paris tidligere i år. Og det lød som om det var spiseligt.

Det er ret enkelt:

1 kg knoldselleri
20 g mayonnaise
2½ spsk dijon sennep
1 tsk salt
2 spsk citronsaft
Peber

Knoldsellerien skrælles, og skæres i småstykker. Sådan ca. som tændstikker. Sellerien vendes med mayo, sennep, citronsaft. Og smages til med salt og peber.

Mayonaisen er naturligvis hjemmerørt. Det skræmmer mange. Men det er der ingen grund til! Opskriften er så enkel som det kan blive:

Mayonaise
2 æggeblommer
3 dl rapsolie
2 spsk dijon sennep
Salt
Æblecidereddike

Æggeblommerne piskes voldsomt med salt, sennep og en sjat eddike. De skal være tykke og hvide. Dernæst tilsættes olien. Dråbevis i første omgang, senere i en tynd stråle. Fortsæt med at hælde olie i til mayoen er tung og skælver. Basalt set til det ligner mayo. Smag til lidt med mere fint salt og eddike.

Der er to små tricks. Olien og æggeblommerne skal have samme temperatur. Så stil dem på køkkenbordet en times tid eller to inden du går i gang. Brug en neutral olie. Den må godt være god, men lad dig ikke friste til at bruge den dyre olivenolie. Det giver en kedelig smag i mayonaisen.



Hovedretten:

Der er god tid. Så det skal være noget der står og hygger sig længe i gryden. Svinekæber er altid et hit. Kartoffelmos - med parmasanost. Perleløg. Råsyltede rødbeder. Og en portvinssauce.

Opskrifterne er lidt på slump. Når jeg er i det salte køkken følger jeg sjældent opskrifter helt præcist.

Braisserede svinekæber
10 svinekæber
1 liter porter
1 dl balsamicoeddike
2 løg. Eller tre hvis de ikke er så store.
3 fed hvidløg
3 gulerødder. Eller fire. Gulerødderne giver sødme, så pas på med at give for mange.
4 laurbærblade
2 stk stjerneanis
3 kviste rosmarin
1 helt bundt timian
8 peberkorn
Rigeligt smør
Salt

Puds kæberne af for sener, gnid dem med salt. Og smid dem i køleskabet. Det gør jeg klokken tidligt, de tager ikke skade af at ligge i 12 timer - men så tidligt står jeg dog ikke op.
Steg kæberne i masser af smør - brug gerne en støbejernsgryde, og sørg for at de får god varme, så de får stegeskorpe.
Sauter løg, hvidløg, gulerødder og laurbærbladene. Du har selvfølgelig skrællet, pillet og hakket på forhånd. Hæl balsamicoen i, og kog en smule ind.
Alle andre ingredienser hældes i gryde, og der tilsættes vand til kæberne er dækket. Sænk varmen - helt ned til at gryden kun akkurat er i kog, og lad det hele simre i fire timer.
Fisk kæberne op, filtrer braisseringsvæsken. Tag et par dl fra til senere brug, og kog resten ind. Sådan ca. til sirupskonsistens. Vend kæberne i lagen, og varm dem igennem.

Kartoffelmos - med parmasan
Kartofler
Smør
Fløde
Parmasanost (revet)
Hvid peber
Muskatnød (revet)

Det gider jeg ikke udpensle. Men riv parmasanen før du går igang med at mose kartofler. Der skal forholdsvist meget i, og mosen skal helst ikke blive alt for kold, mens du står og fumler med rivejern og ost. Det er også et godt trick at smelte smørret i fløden, så man ikke hælder kolde ting ned til kartoflerne. Af hensyn til anretningen, skal mosen ikke være for lind.

Glaserede perleløg
2 glas perleløg
2 dl sukker
25 gram smør

Samme princip som brune kartofler. Smelt sukkeret til en mørk karamel, tilsæt smør, rør godt rundt. Tilsæt perleløgene. Og rør godt rundt. En vigtig pointe her: Sørg for at løgene er dryppet godt af. Rigtigt godt. Jo mere vand der er på dem, jo sværere er det at få karamellen til at hæfte.

Råsyltede rødbeder
5 rødbeder - lidt afhængig af størrelsen
2 rødløg
2 dl balsamicoeddike
2 dl vand
1 spsk sukker
5 peberkorn
1 laurbærblad
3 spsk olivenolie

Kog eddiken, vand, sukker og krydderier sammen.  Lad lagen køle helt af.
Skræl rødbederne. Fortsæt med at skrælle dem i lange, tynde flager. Kartoffelskrælleren er udemærket til formålet.
Smid dem i iskoldt vand.
Pil rødløgene, og skær dem i meget tynde ringe. Et mandolinjern er godt, hvis ellers du orker at gøre det rent bagefter.
Bland løgringe, rødbedestrimler (lad dem dryppe godt af), lagen og olivenolie sammen, og lad det hygge sig i køleskabet et par timer.

Portvinssauce
2 dl braisseringsvæske fra kæberne
5 dl god kalvefond
3 dl portvin

Portvin og kalvefond (brug bare Oscars fra pulver. Den er faktisk ret god), koges ind. Det kan du gøre i god tid, når kæberne er nået dertil hvor du har et par dl braisseringsvæske, tilsætter du dem, og koger ind til du synes konsistensen er rigtig. Den skal være ret tyk.

Anretning

De store, pæne, tallerkener i vores stel kommer på bordet. En kæbe, en klat kartoffelmos i en madring. Jeg har nogen hjerteformede ringe jeg vil prøve at bruge.  5-6 strimler rødbeder og et par løgringe. En spiseskefuld perleløg. Og så lidt af portvinssaucen anrettet på den der fancy måde i en stribe der gør sig godt på hipstergram. Hertil en god rødvin.

Dessert:

Her går vi efter en lille symfoni af is. Symfoni fordi det lyder fancy. Is, fordi jeg har et par opskrifter der skal testes og udvikles lidt på. Og fordi det er lidt tid siden jeg sidst havde ismaskinen i sving.

Rosenpeberis
Jordbæris
Chokoladeis

Og det er nok bare det.

Rosenpeberis

Rosapeber, rosenpeber, lyserød peber. Uanset hvad du kalder det, er det faktisk ikke peber. Det er et bær fra den peruvianske peberbusk, der altså ikke er i familie med egentlig peber. Men det smager lidt af peber.



Sådan ser de ud - du kender dem godt

Nu tænker du måske - peberis?! Det kan da virkelig ikke være godt. Men det er det faktisk. Det bliver aldrig en is man sidder og kører ned i store mængder. Det er en variant, der skal serveres sammen med andre slags is, for at give et eksotisk pift. Alene er den for meget. Sammen med andet er den god. Denne gang bliver det lidt et forsøg. Første gang jeg prøvede, brugte jeg en opskrift der dels gav for meget is (i forhold til størrelsen af vores ismaskine), dels var for stærkt pebret. Så denne gang bruger jeg min standardopskrift, og 7 gram rosapeber.

150 Sukker
2 dl sødmælk
5 dl piskefløde
8 æggeblommer
7 gram rosapeber

Sødmælken bringes i kog med peberkornene, tages af ilden, og trækker 10 minutter.

Dernæst hældes alle andre ingredienser i gryden (piskefløden først, så temperaturen bringes ned), og der varmes op til ca. 80 grader under omrøring. Dernæst passeres det hele gennem en sigte, hældes på ismaskinen (efter at være kølet lidt af). Og når ismaskinen er færdig, ryger det i fryseren og stivner helt.

Jordbæris
250 gram jordbær - jeg bruger bare de frosne
75 gram sukker
½ stang vanille
4 æggeblommer
1 dl sødmælk
2½ dl piskefløde

Vanillestangen flækkes, og kornene skrabes ud. De fordeles i halvdelen af sukkeret.

Den anden halvdel af sukkeret kommer i gryden sammen med den flækkede vanillestang og jordbærrene. Det koges op, og simrer i et par minutter. Blandingen får en tur med stavblenderen, og moses gennem en sigte, så jordbærkernerne - de fleste af dem, sorteres fra.

Resten af sukkeret (det med vanillekornene), æggeblommerne, fløden og mælken hældes i en anden gryde, og varmes op til ca. 80 grader. Nu har vi noget der ligner en creme anglaise. Jordbærpureen røres i cremen. Efter den er kølet af, kommer den på ismaskinen, og derefter i fryseren.

Chokoladeis

Jeg har en pæn sjat lys belgisk chokolade af god kvalitet. Men der er lige i underkanten til at gå i gang med at lave fyldte chokolader. Så den kommer i isen.

Her kører vi igen standardvanillieis opskriften - igen uden vanille.  Jeg tilsætter efter cremen er blevet siet, et par gode håndfulde chokolade til den, og rører godt rundt. Hvorefter den kommer på ismaskinen og derefter i fryseren. Da chokoladen er sød - skærer jeg lidt ned på sukkermængden i opskriften.

* 100 gram sukker
* 2 dl Sødmælk
* 5 dl Piskefløde
* 8 æggeblommer
* 160 gram lys chokolade

Alle ingredienser bortset fra chokoladen hældes i en gryde og varmes langsomt op til 80 grader under omrøring. Ismassen køres gennem en sigte, og chokoladen tilsættes. Den chokolade jeg har stående kommer i små tabletter. Ellers havde jeg hakket den fint, for at få den til at smelte hurtigere i den varme ismasse. Der røres grundigt, og ismassen hældes på ismaskinen. Den kvikke trafikkanin kan nu godt regne resten af processen ud.

Det kan godt være der går lidt pyntepia i det når den anrettes, men det bliver basalt set en kugle af hver på en asiet, og så på bordet.
