# omregninger og mængder

Ved kogning af pasta er reglen:

1000/100/10. Som i 1000 g vand, 100 g pasta og 10 g NaCl



## US- til civiliserede mål

* 1 oz ~ 28 gram
* 375 F ~ 190 grader C
* 1 cup = 273 ml
* 1 pint = 2 cups = 546 ml


## Volumen/vægt

### Generelt

* 1 spsk = 15 ml
* 1 tsk = 5 ml

### Specifikke


* 1 spsk groft salt = 22 gram
* 1 tsk groft salt = 7 gram



## Mængder

### pastasalat til madpakke

Vi skal have mængderne på plads her!

300 gram tør discount fusili vejer 
681 gram kogt.

Så skal vi have styr på hvor meget der skal til for at gøre det ud for frokost. Og så 
finde ud af hvor meget det fylder - så beholder størrelse kan justeres.

Testet 21. januar.

2229 gram pastasalt, inklusive den hvide margretheskål.

Så spiste vi begge to - vi fik nok. Og skålen, inklusive
resten af salaten vejede 1359 gram

Resten af pastasalaten vejede - uden emballage 625 gram.

Salaten blev lavet af ovenstående 681 gram pasta, 240 gram 
majs, 200 gram salattern og 250 gram tomater. Hertil rigelige 
mængder thousand island dressing

Vi fik med andre ord 870 gram pastasalat i alt, eller 435 gram hver.

Og ialt blev der produceret 
2229-1359 = 870, det vi spiste.
+ 625 gram, det der var til rest.
Så i grove træk får vi 1495 gram pastasalat af at koge 300 gram 
tør pasta. Hvis vi regner med 500 gram færdig pastasalt, 
går der derfor 100 gram tør pasta til en frokostportion pastasalat


Vi kan yderligere notere, at et 3/4 liters fido sylteglas med 
patentlukning, uden de store problemer holder ca. 500 gram 
pastasalat. Det er nu min madpakkebeholder!