# Pasta

## Carbonara ala noma

100 gram pancetta - eller bacon i små tern
200 gram tør pasta
25 g røget svampe garum
4 store æggeblommer
100 g pecorino Romano fint revet
salt og peber

Bring vand i kog - med salt. Ikke så meget at det smager salt.
Men så det smager som om det har fået noget.

Steg, ved lav varme, baconen. Den må godt stege, men ikke sprøjte.
Målet er at få fedtet ud uden at baconen bliver mørk.

Fjern 3/4 af fedtet og placer det i en stor skål. 
Steg resten af baconen til den er sprød. Den, og fedtet føres til separat skål.

I den store skål fra før, tilsættes garum, æggeblommer og pecorino.
Bland godt til en pasta

Kog pastaen til den er lige under al dente. Sigt pastaen i dørslag.
Men gem vandet. 

Tilføj lidt af det varme pastavand til skålen og rør voldsomt.
Når den ikke længere er stiv, hældes pastaen i, sammen med friskkværnet
peber og bland godt. Giv evt lidt mere pastavand hvis den er for tør.
Smag til med salt. 

Server i skåle med den sprøde bacon ovenpå, mere peber og et solidt
drøs pecorino. 
Hvis ikke sovsen tykner så sæt den på vandbad (så - pastagryden?).
Men pas på den ikke får for meget varme.

## Peberpasta

En Caico e pepe variant 

* 320 gram pasta
* 4 spsk smør (eller oliven olie)
* 2 1/4 spsk peber - gerne Triple Lemon Pepper fra Mill & Mortar
* 2½ dl revet parmasan
* hakket persille eller basilikum

Kog pastaen til den der er al dente. Dræn, gem kogevand.

Rør pasta sammen med smør i pande eller stor gryde. Tilsæt peber og 2-3 dl
kogevand. Rør mere rundt under god varme.

Tag af kogepladen og tilsæt os. Andret med basilikum eller persille.

Server med stegt kylling, godt brød eller lignende.

## Misopasta

* 310 gram  pasta - linguine eller bucatini
* 6 spsk smør
* 3 spsk miso (sådan en vejer 18 gram)
* 100 gram revet parmasan

Bring vand i kog, og kog pastaen.

Imens samler vi smør og miso i en gryde eller lignende - jeg
bruger min sauterpande. Der røres ret grundigt rundt.
Tilsæt den næsten færdige pasta og 2½ dl eller så kogevand
fra pastaen. Samt parmasanen. Rør aggresivt, indtil 
osten er smeltet og sovsen danner en emulsion.

Bum. Server evt noget kylling i skiver, en grøntsag eller noget.



## Mac n Peas

* 600 g frostærter
* 310 g makaroni
* 50 g smør
* 3 fed hvidløg
* 60 g parmasan

Kog ærter og makeroni
Hak hvidløg fint, og lun i smørret på sauterpanden
Overfør de fleste af ærterne til panden, og stavblend sammen med parmasanen (og salt og peber)
De resterende hele ærter, evt også lidt kogevand, samt makeroni røres sammen med ærtemosen i panden.

Server et par af Faktas (nu 365s) flutes til.



## Pasta al Dante


Dante skrev i følge overleveringen sine digte på en plads med udsigtover byggepladsen hvor Duomoen blev bygget. I følge rygterne havde han en overmenneskelig hukommelse.
En forbipasserende skulle have spurgt ham hvad der var bedst at spise. Og han svarede prompte "æg". Den samme forbipasserende fandt hm et år senere siddende samme sted, og spurgte "Med hvad". Hvortil Dante skulle have svaret, lige så prompte - "Med salt".

Ingredienser

* 300 g bucatini
* 2 af faktas flutes
* 3 fed hvidløg
* Æg
* lidt chiliflager


## Italiensk pølseret

Eller "Pasta con Salsiccia e Tartufo"

Superenkel ret. Og det er jo altid godt.

En pakke små italienske pølser
Trøffelpasta mindst 3 tsk
1½ dl hvidvin
2½ dl fløde
1 stilk frisk rosmarin
1 dl god olivenolie
Revet parmasan
Pasta - gerne rigatone

Pil skindet af pølserne, og hak dem. Lad dem simre i en pande med olien i 5 minutter.

Tilsæt rosmarin, 1 tsk trøffelpasta og hvidvin. Kog alkoholen af, og tilsæt fløden.

Kog pastaen. Nu er timingen vigtig. Sovsen skal have kogt ind til rette tykkelse, ca. samtidig med at pastaen er færdig. Man kan snyde og koge sovsen ind, og så tage den af pladen mens man koger pasta.

Vend pasta og sovs sammen, giv den yderligere 2-3 tsk trøfelpasta og nogle solide rev parmasan.

Det er min erfaring af pølserne giver tilstrækkeligt salt og peber, men smag lige til undervejs.



## Standard pastabix

## Onepot Pasta


## Putanesca

også kendt som Luderpasta
Ingredienser

* 200 g sorte oliven
* 2 spsk kapers
* 4-5 rensede ansjoser
* 3 fed hvidløg
* 1-2 peperocini
*1 dåse flåede tomater
* 1 spsk revet citronskal
* 1 håndfuld persille
* 1 smule olivenolie
* 320 gram spaghetti


Hak det hele fint, hver for sig.

olien varmes op på panden, og hvidløg og peperocini svitses. Hvidløget må ikke blive brunt. Og peberen er en smagssag.

Tilsæt oliven, kapers og ansjoser. Steg lidt under omrøring

flåede tomater tilsættes.

Lad det simre mens pastaen koges.

Smag sovsen til med slat og peber, lidt sukker og hakket persille samt citronskal.

Bland pastaen i. juster evt. tykkelsen af sovsen med pastavandet.

## Aglio et olio

Ingredienser

* 400 g bucatini er passende. Prøv med 410 gram næste gang.
* 4 fed hvidløg, finthakket
* 4 spsk god olivenolie
* parmasan - 53 gram er for lidt
* hakket persille - en håndfuld.
* Chili - nok bedre med en peperonici eller hvad den nu hedder En enkelt tørret chili er passende

Hak chili og hvidløg, og lun i olien i sauterpanden. Det går hurtigt, så det kan godt vente til pastaen er i vandet.

Kog pastaen til den er al dente,
Vend pastaen i olien og rør sammen med parmasan og persille

2 af faktas flutes ting til.


## One pot lasagne

Vi så store mængder youtubevideoer. Med en eller anden der ikke hedder Babish, men kalder sig det alligevel. Eller noget.

Ricottaen er pillet ud. 2 klodser moz er fint. En karton pizzasovs, og en enkelt dåse hakket tomat er også nok.
400 gram hakket ko.
Og så kom jeg i første omgang noget der minder om 15 lasagneplader i - og det var i overkanten.



originalen:

* 10 lasagneplader
* 1 spsk oliven olie
* ½ kg spicy italiensk pølse. Men vi bruger hakket kød
* ½ stort løg
* 2 fed hvidløg
* 1 tsk røde peber flager
* 28 oz knuste san marzano tomater. på dåse
* ½ cup varmt vand
* 8 oz tomatsovs
* 8 oz mozarella
* basilikum. Og sådan

https://basicswithbabish.co/basicsepisodes/onepot-pasta


## Pasta med broccoli

* 400 gram pasta
* 1 stor buket broccoli - eller 2 små, det er sådan de kommer i mit supermarked.
* 5 hvidløg
* 7 ansjosfilleter (i olie)
* Chili/peperoncini eller lign. et mellemstort nip
* olie
* peber
* Revet parmasam

Skær broccoli i små buketter, skræl og skær stokken ud i mindre stykker.

Kog broccolien i let saltet vand - til den stadig er relativt fast. Si vandet fra broccolien.

Sæt pastaen over. 10 gram salt per liter vand.

Hak hvidløg og ansjoser, og steg hvidløgene i olivenolie i en sasuterpande sammen med chilien i et par minutter. Tilsæt ansjoserne, og steg videre til fisken er smeltet. Giv det evt lidt pastavand hvis det bliver tørt.

Smid broccolien i panden, og steg dem med.

Det skal først ske når pastaen er næsten færdig, ellers bliver broccolien let for smattet.

Smid den al dente pasta i panden, bland, og tilsæt parmasan, smag til med peber og juster med pastavand.

## Gnocchetti

Bittesmå gnocchi. Lækkert.

Lige dele pr volumen (sådan ca. der skal måles efter) af tipo-00 og ricotta,
helt den fuldfede i stedet for den fedtreducerede æltes sammen med ½ tsk salt
(hvs det er ca. 250 gram af hver).
Hviler på køl, trilles ud til pølse i ca. blyantstykkelse.
Hakkes ud i ca. 1 cm længde.
Koges - de skal have et par minutter efter de har fundet op til overfladen.

Serveres med noget tomatsovs. Eller bare god parmasan. Der skal en sjat mere 
til for at det rækker til os to.


## Sticky Honey Garlic Sausage Pasta Skillet
Ingredients:
* 1 lb Italian sausage (or your choice of sausage)
* 12 oz pasta (penne, rigatoni, or your preferred type)
* 2 tbsp olive oil
* 4 cloves garlic, minced
* 1/4 cup honey
* 2 tbsp soy sauce
* 1 tbsp Dijon mustard (optional)
* 1/2 tsp red pepper flakes (optional, for a spicy kick)
* Salt and pepper, to taste
* Fresh parsley or basil, chopped, for garnish
* Grated Parmesan cheese (optional, for topping)

Og her kan der skrues en del op for chilipeberen.

Instructions:
Cook the pasta: In a large pot, bring salted water to a boil. Add the pasta and cook according to package instructions until al dente. Drain and set aside.
Cook the sausage: While the pasta is cooking, heat olive oil in a large skillet over medium heat. Add the sausage (remove the casing if using link sausage) and cook until browned, breaking it up into small pieces as it cooks. This should take about 5-7 minutes.
Make the sauce: Add the minced garlic to the skillet with the sausage and cook for 1-3 minutes, until fragrant. Stir in the honey, soy sauce, Dijon mustard (if using), and red pepper flakes. Allow the mixture to simmer for 4-6 minutes until the sauce thickens slightly.
Combine pasta and sauce: Add the cooked pasta to the skillet, tossing to coat the pasta in the sticky sauce. Let everything cook together for another 2-3 minutes, allowing the flavors to meld.
Season: Taste and season with salt and pepper as needed.
Serve: Garnish with fresh parsley or basil, and top with grated Parmesan cheese if desired. Serve warm and enjoy your sticky honey garlic sausage pasta skillet!

### Pasta med broccoli

Lad os bare være ærlige - den er nappet fra James Price.

400 gram pasta
1 stor buket broccoli - eller 2 små, det er sådan de kommer i mit supermarked.
5 hvidløg
7 ansjosfilleter (i olie)
Chili/peperoncini eller lign. et mellemstort nip
olie
peber
Revet parmasam

Skær broccoli i små buketter, skræl og skær stokken ud i mindre stykker.

Kog broccolien i let saltet vand - til den stadig er relativt fast. Si vandet fra broccolien.

Sæt pastaen over. 10 gram salt per liter vand.

Hak hvidløg og ansjoser, og steg hvidløgene i olivenolie i en sasuterpande sammen med chilien i et par minutter. Tilsæt ansjoserne, og steg videre til fisken er smeltet. Giv det evt lidt pastavand hvis det bliver tørt.

Smid broccolien i panden, og steg dem med.

Det skal først ske når pastaen er næsten færdig, ellers bliver broccolien let for smattet.

Smid den al dente pasta i panden, bland, og tilsæt parmasan, smag til med peber og juster med pastavand.



### One-Pan Sweet & Tangy BBQ Sausage Rice 

NB ikke pasta. Men...

* 450 g røget pølse - skåret i skiver
* 300 g ris
* 1 peberfrugt - i tern
* 1 løg - i tern
* 2 fed hvidløg - hakket
* ½ l kyllingefond
* 1½ dl BBQ-sovs
* olivenolie
* 1 tsk røget paprika


    ½ tsp garlic powder

    ½ tsp onion powder

    ¼ tsp black pepper

    Pinch of red pepper flakes (optional, for heat)

(Optional garnish: Chopped parsley or green onions)


Brun pølseskiverne i olien i 3-4 minutter. Tag dem fra.
Sauter grønsagerne i ca. 3 minutter
Rør hvidløg i og giv dem lidt varme.

3. Add Rice & Seasonings

Pour in rice, smoked paprika, garlic powder, onion powder, black pepper, and red pepper flakes. Stir to coat.

4. Simmer to Perfection

Add chicken broth and BBQ sauce, then return sausage to the pan.
Bring to a boil, then reduce heat to low, cover, and simmer 18-20 minutes until rice is tender.

5. Serve & Enjoy!

Fluff rice with a fork, drizzle with extra BBQ sauce, and garnish with parsley or green onions.


## One Pot lasagne


Vi så store mængder youtubevideoer. Med en eller anden der ikke hedder babish, men kalder sig det alligevel.

Ricottaen er pillet ud. 2 klodser moz er fint. En karton pizzasovs, og en enkelt dåse hakket tomat er også nok.
400 gram hakket ko.
Og så kom jeg i første omgang noget der minder om 15 lasagneplader i - og det var i overkanten.
https://basicswithbabish.co/basicsepisodes/onepot-pasta


originalen:
10 lasagneplader
1 spsk oliven olie
½ kg spicy italiensk pølse. Men vi bruger hakket kød
½ stort løg
2 fed hvidløg
1 tsk røde peber flager
28 oz knuste san marzano tomater. på dåse
½ cupå varmt vand
8 oz tomatsovs
8 oz mozarella
basilikum. Og sådan

https://basicswithbabish.co/basicsepisodes/onepot-pasta

## Makaronipie
En af Metas opskrifter.
75 g makaroni koges i

4 dl mælk

3 æggeblommer røres med

75 g sukker. Deri kommes

3 dl mælk, 75 g smeltet margarine og de piskede hvider.

Makeroni vendes i og bages ca 1 time.

Hvor længe der skal bages skriver Meta ikke noget om.


## Pasta med knuste ærter
Inspireret af Hugh-Fearnley-Whittingstall

600 g frosne ærter
350 g pasta - det fungerer bedst med de små typer.
50 g smør
2 fed hvidløg - finthakket
25 g revet parmasan
Salt og peber

Ærterne hældes i gryde og dækkes med vand. Bring det i kog, og kog til ærterne er møre. Der er mere smag i friske ærter, men de skal koge længere.

Heromkring koges pastaen. Det skal måske justeres lidt afhængig af pastatypen, og hvor hurtigt man forventer at de næste trin kan gøres.

Smelt smørret i en mindre gryde. Lav varme, det skal ikke brune. Steg hvidløget i smørret - hvidløget må heller ikke tage farve.

Gem et par kopper af vandet fra ærterne, og hæld resten fra. Smid halvdelen af ærterne i gryden med ca. 1 dl af kogevandet og osten. Blendt med stavblender til pureen er glat. Juster evt med lidt mere vand. Hæld resten af ærterne i gryden og smag til med salt og peber.

Hæld vandet fra pastaen, og vend den med ærtepureen. Giv den et strøg parmasan eller tre, og server med brød.









