# Rester

Vi skal af med resterne

## Standardmåder

* Standard pastabix - Se under pastaretterne
* Bixemad


## Gratin

Dette er basisopskriften. Den skal bruges til at skaffe os af med rester.


- 100 g smør
- 150 g mel
- 3 dl grøntsagsbouillon
- 3 dl sødmælk
- 8 æg
- salt, peber, rasp

mindst 50 gram rester, men den kan sagtens trække en del mere.
Skær resterne i mindre stykker

Smelt smør, rør sammen med mel. Lav grundlæggende en opbagt
sovs med væsken.
Del æggene, tag gryden af varmen, og rør blommerne i,.

Pisk hviderne stive, vend halvdelen i gryden sammen med fyldet.

Vend resten af hviderne i. Smør et fad/skål 
og drys med rasp. drys rasp over gratinen, bag nederst i ovnen
ved 175 grader i ca. 1 time. Server med smeltet smør.

## Kartoffelmosfrikadeller

Eller - det har intet med frikadeller at gøre, frikadeller skal laves af de dele af svinet der er så ringe, at vi ikke kan sælge det til englænderne, ellers er det ikke frikadeller.

- 500 gram kartoffelmos
- 1 revet løg
- 1 æg
- 3-4 spsk mælk
- 2-3 spsk hvedemel
- 4-5 spsk rasp
- salt og peber

Alt røres sammen, massen formes til frikadelle-formatet, og steges 2-3 minutter på hver side i rigeligt smør, til de er gyldne. Læg dem til afdrypning på køkkenrulle. Server som tilbehør.

## Bagt pasta uden regler

En opskrift fra Nemlig. Der kan kommes mange forskellige ting i. Svampe og gourgette fungerer fint.
Der kan sikkert også komme kød i. Her ender de der grøntsags rester der ellers ville skulle smides ud i næste uge.

- 2 spsk olie/smør
- 1 løg
- 3 fed hvidløg
- 400 gram aubergine/svampe/kål
- 1 tsk chiliflager/oregano
- 1 spsk tomatpure
- 2 spsk kapers/oliven uden sten
- 400 g hakkede tomater
- 1 dåse hvide bønner/kikærter/baked beans
- 1 tsk sukker/honning
- 500 pasta
- 1 dl rasp
- 50 g revet hård ost

Varm ovnen op - 225 gram varmluft
pil og hak løg og hvidløg
skær grøntsager i små tern
hak kapers eller oliven fint
steg løg og hvidløg i olien/smørret
tilsæt grøntsager og tørrede krydderier til panden. Steg en fem minutter. Eller så langt som det nu skal have.
tilsæt tomatpure og steg kort
tilsæt kapers/oliven og steg videre
tilsæt tomat. Smag til med eddike sukker/honning, salt og peber
kog pastaen
vend kogt pasta i sovsen. Tilsæt evt pastavand hvis det bliver for tørt.

Bland rasp og ost.

Smid pastablandingen i ovnfast fad, drys rasp/ost blandingen over.
Bag under grill i 7 minutter.