# Specialiteterne

## Konfiterede hvidløg

Et lille sylteglas fyldes med pillede hvidløg

Salt kommes i (hvor meget?) sammen med krydderier.

rosmarin og rosenpeber skulle være godt.

Så fyldes glasset med en god olie og låget lukkes til.

Sous vides det i 3-4 timer på 87 grader


## Saltede æggeblommer

Fyld et par centimeter fint (IKKE groft) salt i en bøtte.
Skil blommer fra æg, og placer dem på saltet. Dæk fuldsændigt med salt
Lad stå i køleskabet 8 timer. 
Pil æggeblommerne op af saltet, skyl dem i koldt vand, tør dem. Og 
tør dem i ovnen vad 60 grader - 2 timer er for lidt, opskriften sagde også 3.
De er for gummiagtige, så de skal have længere end det.

Målet er at de skal kunne rives. Så de skal være ret hårde og tørre.

## sous vide kold kaffe
½ cup (så volumen mål) groft kværnet kaffe
4 cup vand

kaffe og vand i vandtæt syltetøjsglas. Sousvides i 2-4 timer ved 150 grader F.

Filtrer, og server hældt over is, eller opbevar på køl i en uges tid. 
Overvej om den skal fortyndes.

## Kaffesmør
Det her skal prøves! 

Oversættelsen må være "kaffesmør", men originalen kalder det for Uber fantastic Coffee Butter: http://www.instructables.com/id/Uber-fantastic-Coffee-Butter/.

En spsk fintmalet kaffe
En spsk jordnøddesmør
En tsk honning eller sukker.

De skriver ikke noget om hvilken slags jordnøddesmør der skal til. Men jeg vil gætte på at det ikke skal være crunchy.

## Ærtepesto

2 dl ærter - friske er selvfølgelig pr definition bedst. Men så skal de blancheres først.
1 fed hvidløg
1 dl mandler (smuttede)
½ dl olivenolie
2 spsk citronsaft
salt og peber

Rist mandlerne på panden til de er gyldne og sprøde. Gerne med lidt salt.

Alle øvrige ingredienser stavblendes, og der smages til med salt, peber og citronsaft. Hak mandlerne og rør dem i ærtepestoen.