# Specialiteterne

## Konfiterede hvidløg

Et lille sylteglas fyldes med pillede hvidløg

Salt kommes i (hvor meget?) sammen med krydderier.

rosmarin og rosenpeber skulle være godt.

Så fyldes glasset med en god olie og låget lukkes til.

Sous vides det i 3-4 timer på 87 grader


## Saltede æggeblommer

Fyld et par centimeter fint (IKKE groft) salt i en bøtte.
Skil blommer fra æg, og placer dem på saltet. Dæk fuldsændigt med salt
Lad stå i køleskabet 8 timer. 
Pil æggeblommerne op af saltet, skyl dem i koldt vand, tør dem. Og 
tør dem i ovnen vad 60 grader - 2 timer er for lidt, opskriften sagde også 3.
De er for gummiagtige, så de skal have længere end det.

Målet er at de skal kunne rives. Så de skal være ret hårde og tørre.

## sous vide kold kaffe

- ½ cup (så volumen mål) groft kværnet kaffe
- 4 cup vand

kaffe og vand i vandtæt syltetøjsglas. Sousvides i 2-4 timer ved 66 °C.

Filtrer, og server hældt over is, eller opbevar på køl i en uges tid. 
Overvej om den skal fortyndes.

## Kaffesmør
Det her skal prøves! 

Oversættelsen må være "kaffesmør", men originalen kalder det for Uber fantastic Coffee Butter: http://www.instructables.com/id/Uber-fantastic-Coffee-Butter/.

- En spsk fintmalet kaffe
- En spsk jordnøddesmør
- En tsk honning eller sukker.

De skriver ikke noget om hvilken slags jordnøddesmør der skal til. Men jeg vil gætte på at det ikke skal være crunchy.

## Ærtepesto

- 2 dl ærter - friske er selvfølgelig pr definition bedst. Men så skal de blancheres først.
- 1 fed hvidløg
- 1 dl mandler (smuttede)
- ½ dl olivenolie
- 2 spsk citronsaft
- salt og peber

Rist mandlerne på panden til de er gyldne og sprøde. Gerne med lidt salt.

Alle øvrige ingredienser stavblendes, og der smages til med salt, peber og citronsaft. Hak mandlerne og rør dem i ærtepestoen.


## Håndsprit

Ja, det er faktisk alvorligt. Måske ikke for dig. Men hvis fem procent af de der bliver smittede med Corona-virusen skal indlægges, og halvdelen af landets befolkning på 5,8 millioner bliver smittet - så er det 145.000 mennesker der skal indlægges. Hvordan tror du selv at det danske sundhedsvæsen vil håndtere den opgave?

Anyway. Flydende håndsprit kan laves efter disse opskrifter. En af dagene ser jeg om jeg kan få skruet en opskrift på en gel sammen.

Du skal bruge:

- 99% isopropylalkohol eller 93% husholdningssprit.
- Glycerin
- Brintoverilte 3%
- Vand

Det hele kan findes hos en materialist. Hvis du kan finde sådan en. Matas er jo en parfumeforretning nu.

40 ml brintoverilte blandes med 15 ml glycerin.

Hvis du bruger husholdningssprit fortyndes den blanding til 160 ml med vand. Og fortynd den blanding til 1 liter med husholdningssprit.

Hvis du bruger isopropylalkohol, fortyndes blandingen til 240 ml med vand. Og den blanding fortyndes så til 1 liter med isopropylalkohol.





