# Supperne

## Løgsuppe

* 1½ kg løg
* 3-400 g gruyere eller comtè ost
* 1-1½ l oksebouillon
* 1 glas hvidvin
* 1 lille glas cognac
* 2-3 stk. laurbær
* 1 kvist frisk timian
* 2-3 spsk. smør
* 8-10 stk. sorte peberkorn
* 2 spsk. hvedemel
* 1 flute

Pil og skær løgene tyndt. Svits dem langsomt i rigeligt smør og 
en sjat olivenolie, til de er mørkebrune og karameliserede. Det tager
en times tid. Rør regelmæssigt, så de ikke brænder på.

Drys mel over og bag igennem. Tilsæt hvidvin og bouillon. Det er bouillonen
der gør forskellen. Kom krydderier i te- eller gazepose, og smid i.

Lad det simre ca. 20 minutter, og pil posen op igen. Smag til med
cognac, evt. sherryvineddike, salt og peber.

Rist skiver af flute - jeg smider dem i airfryeren. De skal være meget
tørre. 

Hæld suppe i skål, læg fluteskiver ud som små tømmerflåder, og vælt 
voldsomme mængder ost oven på. Ind i ovnen under grill, og giv dem til
de er lysebrune og gratinerede. Men pas på! Det går hurtigt.

Husk også at når de kommer ud af ovnen. Da er den smeltede ost måske ikke
300 grader varm. Men den føles som.

## Hollandsk ærtesuppe - eller Snert - eller Ertwensoop

Fik vi første gang på en mormor restaurant i Amsterdam.

Det svære er at finde de grønne flækærter, men de har demi i 
INCO.

Egentlig skal der selleri i. Så opskriften er modificeret.

* 500 gram grønne flækærter
* 1 porre (eller tre små hvis det er den mængde de kommer i)
* 2 liter vand
* 3 ko-bouillon terninger
* 2-3 store gulerødder
* 1 stor kartoffel (250 gram)
* Røget pølse - 275 gram. Kålpølser fra slagter lampe er fine
* 300 gram nakkekoteletter
* 3 laurbærblade 
* 1 løg

Skyl ærterne, og bring vand, bouillon, ærter og laurbærblade i kog.
Tilsæt nakkekoteletterne og pølserne. Lad simre i ca. 1 time, rør og skum af. Og fisk
koteletter og pølser op når de er ved at være færdige.

Skræl, skyl etc. grøntsagerne, og skær dem i kuber af ca 1x1x1 cm. Eller deromkring. Porrene i ringe, løget hakket. 

Efter en times tid er ærterne ved at gå i opløsning. Rør grundigt - det fremmer
processen. 

Tilsæt grøntsagerne og lad simre yderligere ½ times tid - eller til grøntsagerne 
er møre. 

Skær koteletter og pølser i mundrette bidder, og smid dem i gryden til de
er varme igen. Smag til med salt og peber. 
Server med groft brød.