---
title: "Det søde"
format:
    html:
        toc: true
        number_sections: true
---


## Kandiseret frugt

Fra bogen "Farmacevtens andet Aar i Radio"  @farmaradio.

Forbered frugtstykkerne. Druer, æblestykker, appelsin etc.

Fremstil en sukkerlage af 250 sukker, 1 dl vand, 1 tsk eddike og 1 tsk druesukker. Bring først sukker, druesukker og vand i kog, skum af og tilsæt eddike. Når lagen er kogt tilstrækkeligt ind - en dråbe af lagen dryppes i koldt vand - den skal blive sprød som glas.

Dyp hurtigt frugten i lagen og læg dem til tørre på et fad - smurt med olie eller smør.

## Flødekarameller

Fra bogen "Farmacevtens andet Aar i Radio", @farmaradio

* Kog 150 g sukker med 100 g fløde.

* Og 150 g sukker med 25 g smør til karamel.

Alt blandes og æltes. Hæld ud på et fladt fad, smurt med smør eller olie. Lad det stå nogle timer, og udskær i passende firkanter, drys med flormelis.

## Karamel æbler

En opskrift fra det gamle DDR. Hentet på DDR museet i Berlin. Og de havde den fra "Kuchen, Torten und Gebäck" fra 1971. Udgivet på "Verlag für die Frau". Jeg ved ikke om det i dag betragtes som meget misogynt, eller meget progressivt, at der var et forlag for kvinder.

Anyway:

- 60 g sukker
- 2 spsk honning
- næsten 250 ml vand
- saften af en citron
- 4 store madæbler
- 120 g mel
- 2 spsk sukker
- 1 nip salt
- 2 æg
- Olie
- Flormelis.

80 g sukker, honning, 125 ml vand, og citronsaft blandes, og koges ind til en halvtyk sirup. Skræl æblerne, og skær i kvarte - læg dem i siruppen.

Tag kaserollen af varmen, og lad den stå i 1 time - vend æblerne regelmæssigt.

Imens sigtes melet med salt, og blandes med 2 spsk sukker samt æggeblommerne. Tilføj 125 ml vand, og rør sammen.

Pisk æggehviderne, og fold dem ind i dejen.

Fjern æblerne fra siruppen, og lad dem dryppe lidt af. Dyp dem i dejen, og kog dem i olien til de er brune og sprøde. Lad dem dryppe af på fedtsugende papir, og drys med flormelis.

